package features.dungeon.api;

public enum DungeonTravelRejectionReason {
    NONE,
    INVALID_INPUT,
    NO_ACTIVE_POSITION,
    ACTION_UNAVAILABLE,
    AUTHORED_UNAVAILABLE,
    TRANSITION_UNAVAILABLE,
    OFF_WINDOW,
    NON_TRAVERSABLE,
    UNREACHABLE,
    PARTY_REJECTED,
    PARTY_STORAGE_FAILURE,
    PARTY_FAILURE,
    STALE_PARTY_POSITION
}
