$schema: "https://jqassistant.github.io/jqassistant/current/schema/jqassistant-configuration-cli-v2.6.schema.json"

jqassistant:
  store:
    uri: file:build/jqassistant/store
  scan:
    reset: true
    continue-on-error: false
    include:
      files:
        - java:classpath::build/classes/java/main
        - bootstrap
        - shell
        - src
  analyze:
    rule:
      directory: tools/quality/view-binder-enforcement/jqassistant/rules/
    baseline:
      enabled: false
    report:
      continue-on-failure: false
      fail-on-severity: BLOCKER
      properties:
        xml.report.file: build/reports/jqassistant/jqassistant-report.xml
        xml.report.transform-to-html: false
        junit.report.directory: build/reports/jqassistant/junit
        junit.report.failureSeverity: BLOCKER
        junit.report.errorSeverity: BLOCKER
    groups:
      - saltmarcher:view-binder-enforcement
