#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as ksh or
#       bash, then to run this script, type that shell name before the whole
#       command line, like:
#
#           ksh Gradle
#
#       Busybox and similar reduced shells will NOT work, because this script
#       requires all of these POSIX shell features:
#         * functions;
#         * expansions «$var», «${var}», «${var:-default}», «${var+SET}»,
#           «${var#prefix}», «${var%suffix}», and «$( cmd )»;
#         * compound commands having a testable exit status, especially «case»;
#         * various built-in commands including «command», «set», and «ulimit».
#
#   Important for patching:
#
#   (2) This script targets any POSIX shell, so it avoids extensions provided
#       by Bash, Ksh, etc; in particular arrays are avoided.
#
#       The "traditional" practice of packing multiple parameters into a
#       space-separated string is a well documented source of bugs and security
#       problems, so this is (mostly) avoided, by progressively accumulating
#       options in "$@", and eventually passing that to Java.
#
#       Where the inherited environment variables (DEFAULT_JVM_OPTS, JAVA_OPTS,
#       and GRADLE_OPTS) rely on word-splitting, this is performed explicitly;
#       see the in-line comments for details.
#
#       There are tweaks for specific operating systems such as AIX, CygWin,
#       Darwin, MinGW, and NonStop.
#
#   (3) This script is generated from the Groovy template
#       https://github.com/gradle/gradle/blob/HEAD/platforms/jvm/plugins-application/src/main/resources/org/gradle/api/internal/plugins/unixStartScript.txt
#       within the Gradle project.
#
#       You can find Gradle at https://github.com/gradle/gradle/.
#
##############################################################################

# Attempt to set APP_HOME

# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}  # leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]
do
    ls=$( ls -ld "$app_path" )
    link=${ls#*' -> '}
    case $link in             #(
      /*)   app_path=$link ;; #(
      *)    app_path=$APP_HOME$link ;;
    esac
done

# This is normally unused
# shellcheck disable=SC2034
APP_BASE_NAME=${0##*/}
# Discard cd standard output in case $CDPATH is set (https://github.com/gradle/gradle/issues/25036)
APP_HOME=$( cd -P "${APP_HOME:-./}" > /dev/null && printf '%s
' "$PWD" ) || exit

if [ -f "$APP_HOME/tools/gradle/prepare-isolated-gradle-env.sh" ] ; then
    # shellcheck disable=SC1091
    . "$APP_HOME/tools/gradle/prepare-isolated-gradle-env.sh" || exit $?
fi

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "$( uname )" in                #(
  CYGWIN* )         cygwin=true  ;; #(
  Darwin* )         darwin=true  ;; #(
  MSYS* | MINGW* )  msys=true    ;; #(
  NONSTOP* )        nonstop=true ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar


# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD=$JAVA_HOME/jre/sh/java
    else
        JAVACMD=$JAVA_HOME/bin/java
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
    if ! command -v java >/dev/null 2>&1
    then
        die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
    case $MAX_FD in #(
      max*)
        # In POSIX sh, ulimit -H is undefined. That's why the result is checked to see if it worked.
        # shellcheck disable=SC2039,SC3045
        MAX_FD=$( ulimit -H -n ) ||
            warn "Could not query maximum file descriptor limit"
    esac
    case $MAX_FD in  #(
      '' | soft) :;; #(
      *)
        # In POSIX sh, ulimit -n is undefined. That's why the result is checked to see if it worked.
        # shellcheck disable=SC2039,SC3045
        ulimit -n "$MAX_FD" ||
            warn "Could not set maximum file descriptor limit to $MAX_FD"
    esac
fi

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the main class name
#   * -classpath
#   * -D...appname settings
#   * --module-path (only if needed)
#   * DEFAULT_JVM_OPTS, JAVA_OPTS, and GRADLE_OPTS environment variables.

# For Cygwin or MSYS, switch paths to Windows format before running java
if "$cygwin" || "$msys" ; then
    APP_HOME=$( cygpath --path --mixed "$APP_HOME" )
    CLASSPATH=$( cygpath --path --mixed "$CLASSPATH" )

    JAVACMD=$( cygpath --unix "$JAVACMD" )

    # Now convert the arguments - kludge to limit ourselves to /bin/sh
    for arg do
        if
            case $arg in                                #(
              -*)   false ;;                            # don't mess with options #(
              /?*)  t=${arg#/} t=/${t%%/*}              # looks like a POSIX filepath
                    [ -e "$t" ] ;;                      #(
              *)    false ;;
            esac
        then
            arg=$( cygpath --path --ignore --mixed "$arg" )
        fi
        # Roll the args list around exactly as many times as the number of
        # args, so each arg winds up back in the position where it started, but
        # possibly modified.
        #
        # NB: a `for` loop captures its iteration list before it begins, so
        # changing the positional parameters here affects neither the number of
        # iterations, nor the values presented in `arg`.
        shift                   # remove old arg
        set -- "$@" "$arg"      # push replacement arg
    done
fi


# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m" "--enable-native-access=ALL-UNNAMED"'

# Collect all arguments for the java command:
#   * DEFAULT_JVM_OPTS, JAVA_OPTS, JAVA_OPTS, and optsEnvironmentVar are not allowed to contain shell fragments,
#     and any embedded shellness will be escaped.
#   * For example: A user cannot expect ${Hostname} to be expanded, as it is an environment variable and will be
#     treated as '${Hostname}' itself on the command line.

set -- \
        "-Dorg.gradle.appname=$APP_BASE_NAME" \
        -classpath "$CLASSPATH" \
        org.gradle.wrapper.GradleWrapperMain \
        "$@"

# Stop when "xargs" is not available.
if ! command -v xargs >/dev/null 2>&1
then
    die "xargs is not available"
fi

# Use "xargs" to parse quoted args.
#
# With -n1 it outputs one arg per line, with the quotes and backslashes removed.
#
# In Bash we could simply go:
#
#   readarray ARGS < <( xargs -n1 <<<"$var" ) &&
#   set -- "${ARGS[@]}" "$@"
#
# but POSIX shell has neither arrays nor command substitution, so instead we
# post-process each arg (as a line of input to sed) to backslash-escape any
# character that might be a shell metacharacter, then use eval to reverse
# that process (while maintaining the separation between arguments), and wrap
# the whole thing up as a single "set" statement.
#
# This will of course break if any of these variables contains a newline or
# an unmatched quote.
#

eval "set -- $(
        printf '%s\n' "$DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS" |
        xargs -n1 |
        sed ' s~[^-[:alnum:]+,./:=@_]~\\&~g; ' |
        tr '\n' ' '
    )" '"$@"'

saltmarcher_has_daemon_flag=false
saltmarcher_has_configuration_cache_flag=false
saltmarcher_has_no_configuration_cache_flag=false
saltmarcher_has_project_cache_dir_flag=false
saltmarcher_has_isolation_init_script=false
saltmarcher_init_script_awaits_value=false
saltmarcher_configuration_cache_lock_held=false
saltmarcher_configuration_cache_wait_logged=false
saltmarcher_init_script_path=$APP_HOME/tools/gradle/saltmarcher-isolation.init.gradle.kts
for arg do
    if [ "$saltmarcher_init_script_awaits_value" = true ]; then
        if [ "$arg" = "$saltmarcher_init_script_path" ]; then
            saltmarcher_has_isolation_init_script=true
        fi
        saltmarcher_init_script_awaits_value=false
        continue
    fi

    case $arg in
      --daemon|--no-daemon)
        saltmarcher_has_daemon_flag=true
        ;;
      --configuration-cache)
        saltmarcher_has_configuration_cache_flag=true
        ;;
      --no-configuration-cache)
        saltmarcher_has_no_configuration_cache_flag=true
        ;;
      --project-cache-dir|--project-cache-dir=*)
        saltmarcher_has_project_cache_dir_flag=true
        ;;
      -I|--init-script)
        saltmarcher_init_script_awaits_value=true
        ;;
      -I?*)
        saltmarcher_init_script_value=${arg#-I}
        if [ "$saltmarcher_init_script_value" = "$saltmarcher_init_script_path" ]; then
            saltmarcher_has_isolation_init_script=true
        fi
        ;;
      --init-script=*)
        saltmarcher_init_script_value=${arg#--init-script=}
        if [ "$saltmarcher_init_script_value" = "$saltmarcher_init_script_path" ]; then
            saltmarcher_has_isolation_init_script=true
        fi
        ;;
    esac
done

if [ "$saltmarcher_has_daemon_flag" = false ]; then
    set -- "$@" --no-daemon
fi

if [ "$saltmarcher_has_configuration_cache_flag" = false ] \
    && [ "$saltmarcher_has_no_configuration_cache_flag" = false ] \
    && [ "${SALTMARCHER_GRADLE_AUTO_CONFIGURATION_CACHE:-false}" = true ]; then
    set -- "$@" --configuration-cache
    saltmarcher_has_configuration_cache_flag=true
fi

if [ "$saltmarcher_has_project_cache_dir_flag" = false ] \
    && [ -n "${SALTMARCHER_GRADLE_ROOT_PROJECT_CACHE_DIR:-}" ]; then
    # Root project cache isolation must exist before settings/pluginManagement runs.
    set -- "$@" --project-cache-dir "$SALTMARCHER_GRADLE_ROOT_PROJECT_CACHE_DIR"
fi

if [ "$saltmarcher_has_isolation_init_script" = false ] \
    && [ -f "$saltmarcher_init_script_path" ]; then
    set -- "$@" -I "$saltmarcher_init_script_path"
fi

gradle_pid=
signal_forwarded=
saltmarcher_configuration_cache_lock_dir=${SALTMARCHER_GRADLE_CONFIGURATION_CACHE_WARMUP_LOCK_DIR:-}

saltmarcher_print_failure_hint() {
    if [ -z "${SALTMARCHER_GRADLE_ISOLATION_SEGMENT:-}" ] ; then
        return 0
    fi

    saltmarcher_retained_failures_root=${SALTMARCHER_GRADLE_RETAINED_FAILURES_ROOT:-$APP_HOME/build/retained-gradle-failures}
    saltmarcher_retained_run_root=$saltmarcher_retained_failures_root/${SALTMARCHER_GRADLE_ISOLATION_SEGMENT}
    [ -d "$saltmarcher_retained_run_root" ] || return 0

    echo "Stable failure diagnostics: $saltmarcher_retained_run_root" >&2
    if [ -d "$saltmarcher_retained_run_root/reports" ] ; then
        echo "Retained reports: $saltmarcher_retained_run_root/reports" >&2
    else
        echo "No retained reports were written for this failure; inspect the Gradle error output above for the primary cause." >&2
    fi
    if [ -d "$saltmarcher_retained_run_root/test-results" ] ; then
        echo "Retained test results: $saltmarcher_retained_run_root/test-results" >&2
    fi
    echo "Per-run paths under .gradle/isolated-runs/... are runtime locations and may already be deleted after cleanup." >&2
}

saltmarcher_configuration_cache_ready() {
    [ -n "${SALTMARCHER_GRADLE_CONFIGURATION_CACHE_READY_MARKER:-}" ] \
        && [ -f "$SALTMARCHER_GRADLE_CONFIGURATION_CACHE_READY_MARKER" ]
}

saltmarcher_configuration_cache_warmup_lock_stale() {
    lock_dir=$1
    owner_pid_file=$lock_dir/owner.pid

    [ -d "$lock_dir" ] || return 1
    [ -f "$owner_pid_file" ] || return 1

    owner_pid=$(sed -n '1p' "$owner_pid_file")
    [ -n "$owner_pid" ] || return 1
    if kill -0 "$owner_pid" 2>/dev/null; then
        return 1
    fi
    return 0
}

saltmarcher_release_configuration_cache_warmup_lock() {
    if [ "$saltmarcher_configuration_cache_lock_held" = true ] \
        && [ -n "$saltmarcher_configuration_cache_lock_dir" ] \
        && [ -d "$saltmarcher_configuration_cache_lock_dir" ]; then
        rm -rf "$saltmarcher_configuration_cache_lock_dir"
    fi
    saltmarcher_configuration_cache_lock_held=false
}

saltmarcher_acquire_configuration_cache_warmup_lock() {
    if [ "${SALTMARCHER_GRADLE_CONFIGURATION_CACHE_ACTIVE:-false}" != true ]; then
        return 0
    fi
    if [ "$saltmarcher_has_no_configuration_cache_flag" = true ] || [ "$saltmarcher_has_configuration_cache_flag" = false ]; then
        return 0
    fi
    if [ -z "$saltmarcher_configuration_cache_lock_dir" ]; then
        return 0
    fi
    if saltmarcher_configuration_cache_ready; then
        return 0
    fi

    mkdir -p "$(dirname "$saltmarcher_configuration_cache_lock_dir")"

    while :; do
        if saltmarcher_configuration_cache_ready; then
            return 0
        fi
        if mkdir "$saltmarcher_configuration_cache_lock_dir" 2>/dev/null; then
            printf '%s\n' "$$" > "$saltmarcher_configuration_cache_lock_dir/owner.pid"
            printf '%s\n' "$(date +%s)" > "$saltmarcher_configuration_cache_lock_dir/owner.startedAtEpochSeconds"
            saltmarcher_configuration_cache_lock_held=true
            if saltmarcher_configuration_cache_ready; then
                saltmarcher_release_configuration_cache_warmup_lock
            fi
            return 0
        fi
        if saltmarcher_configuration_cache_warmup_lock_stale "$saltmarcher_configuration_cache_lock_dir"; then
            rm -rf "$saltmarcher_configuration_cache_lock_dir"
            continue
        fi
        if [ "$saltmarcher_configuration_cache_wait_logged" = false ]; then
            echo "Waiting to acquire configuration-cache warmup lock for shared state: $saltmarcher_configuration_cache_lock_dir" >&2
            echo "Another first writer is seeding shared configuration state for the same verification surface." >&2
            saltmarcher_configuration_cache_wait_logged=true
        fi
        sleep 1
    done
}

saltmarcher_mark_configuration_cache_ready() {
    if [ "${SALTMARCHER_GRADLE_CONFIGURATION_CACHE_ACTIVE:-false}" != true ]; then
        return 0
    fi
    if [ "$saltmarcher_has_no_configuration_cache_flag" = true ] || [ "$saltmarcher_has_configuration_cache_flag" = false ]; then
        return 0
    fi
    if [ -z "${SALTMARCHER_GRADLE_CONFIGURATION_CACHE_READY_MARKER:-}" ]; then
        return 0
    fi

    mkdir -p "$(dirname "$SALTMARCHER_GRADLE_CONFIGURATION_CACHE_READY_MARKER")"
    {
        printf 'readyAt=%s\n' "$(date -Iseconds)"
        printf 'ownerPid=%s\n' "$$"
        printf 'sharedStateRoot=%s\n' "${SALTMARCHER_GRADLE_ISOLATED_RUNTIME_ROOT:-}"
    } > "$SALTMARCHER_GRADLE_CONFIGURATION_CACHE_READY_MARKER"
}

forward_signal() {
    signal_name=$1
    signal_forwarded=$signal_name
    if [ -n "$gradle_pid" ] && kill -0 "$gradle_pid" 2>/dev/null; then
        kill "-$signal_name" "$gradle_pid" 2>/dev/null || true
    fi
}

trap 'forward_signal TERM' TERM
trap 'forward_signal INT' INT

saltmarcher_acquire_configuration_cache_warmup_lock
"$JAVACMD" "$@" &
gradle_pid=$!
wait "$gradle_pid"
gradle_status=$?
if [ "$gradle_status" -eq 0 ]; then
    saltmarcher_mark_configuration_cache_ready
fi
saltmarcher_release_configuration_cache_warmup_lock

if [ -f "$APP_HOME/tools/gradle/finalize-isolated-gradle-run.sh" ] ; then
    sh "$APP_HOME/tools/gradle/finalize-isolated-gradle-run.sh" \
        "$gradle_status" \
        "${signal_forwarded:-}"
    finalize_status=$?
    if [ "$gradle_status" -eq 0 ] && [ "$finalize_status" -ne 0 ] ; then
        exit "$finalize_status"
    fi
fi

if [ "$gradle_status" -ne 0 ] ; then
    saltmarcher_print_failure_hint
fi

exit "$gradle_status"
