package saltmarcher.architecture;

enum SourceKind {
    BOOTSTRAP,
    SHELL_HOST,
    SHELL_PANEL,
    VIEW_CONTRIBUTION,
    VIEW_BINDER,
    VIEW_MODEL,
    VIEW_PANEL,
    DOMAIN_ROOT,
    DOMAIN_PUBLISHED,
    DOMAIN_APPLICATION,
    DOMAIN_ROLE,
    DATA_ROOT,
    DATA_REPOSITORY,
    DATA_QUERY,
    DATA_GATEWAY_LOCAL,
    DATA_GATEWAY_REMOTE,
    DATA_PERSISTENCECORE_SQLITE,
    DATA_SCHEMA,
    DATA_MODEL,
    DATA_MAPPER,
    UNKNOWN
}
