package features.world.dungeonmap.repository;

import java.sql.SQLException;
import java.sql.Statement;

/**
 * The tables declared here define the active dungeon truth.
 *
 * <p>When behavior changes, this schema should continue to point at the real owners instead of keeping parallel
 * compatibility state alive.
 */
public final class DungeonStorageSupport {

    private DungeonStorageSupport() {
        throw new AssertionError("No instances");
    }

    public static void createSchema(Statement stmt) throws SQLException {
        stmt.execute("CREATE TABLE IF NOT EXISTS dungeon_maps ("
                + "dungeon_map_id INTEGER PRIMARY KEY AUTOINCREMENT,"
                + "name           TEXT NOT NULL"
                + ")");
        stmt.execute("CREATE TABLE IF NOT EXISTS dungeon_room_clusters ("
                + "cluster_id       INTEGER PRIMARY KEY AUTOINCREMENT,"
                + "dungeon_map_id   INTEGER NOT NULL REFERENCES dungeon_maps(dungeon_map_id) ON DELETE CASCADE,"
                + "center_x         INTEGER NOT NULL,"
                + "center_y         INTEGER NOT NULL,"
                + "level_z          INTEGER NOT NULL DEFAULT 0"
                + ")");
        stmt.execute("CREATE TABLE IF NOT EXISTS dungeon_rooms ("
                + "room_id         INTEGER PRIMARY KEY AUTOINCREMENT,"
                + "dungeon_map_id  INTEGER NOT NULL REFERENCES dungeon_maps(dungeon_map_id) ON DELETE CASCADE,"
                + "cluster_id      INTEGER NOT NULL REFERENCES dungeon_room_clusters(cluster_id) ON DELETE CASCADE,"
                + "name            TEXT NOT NULL,"
                + "visual_description TEXT,"
                + "component_x     INTEGER NOT NULL,"
                + "component_y     INTEGER NOT NULL,"
                + "level_z         INTEGER NOT NULL DEFAULT 0"
                + ")");
        stmt.execute("CREATE TABLE IF NOT EXISTS dungeon_corridors ("
                + "corridor_id      INTEGER PRIMARY KEY AUTOINCREMENT,"
                + "dungeon_map_id   INTEGER NOT NULL REFERENCES dungeon_maps(dungeon_map_id) ON DELETE CASCADE,"
                + "level_z          INTEGER NOT NULL DEFAULT 0"
                + ")");
        stmt.execute("CREATE TABLE IF NOT EXISTS dungeon_wall_kinds ("
                + "wall_kind_id               INTEGER PRIMARY KEY,"
                + "wall_key                   TEXT NOT NULL UNIQUE,"
                + "name                       TEXT NOT NULL,"
                + "blocks_passage             INTEGER NOT NULL DEFAULT 1,"
                + "blocks_sight               INTEGER NOT NULL DEFAULT 1,"
                + "render_style               TEXT NOT NULL,"
                + "supports_door_attachments  INTEGER NOT NULL DEFAULT 1,"
                + "built_in                   INTEGER NOT NULL DEFAULT 0"
                + ")");
        stmt.execute("INSERT OR IGNORE INTO dungeon_wall_kinds("
                + "wall_kind_id, wall_key, name, blocks_passage, blocks_sight, render_style, supports_door_attachments, built_in"
                + ") VALUES(1, 'solid', 'Massive Wand', 1, 1, 'SOLID', 1, 1)");
        stmt.execute("CREATE TABLE IF NOT EXISTS dungeon_doors ("
                + "door_id          INTEGER PRIMARY KEY,"
                + "cluster_id       INTEGER REFERENCES dungeon_room_clusters(cluster_id) ON DELETE CASCADE,"
                + "corridor_id      INTEGER REFERENCES dungeon_corridors(corridor_id) ON DELETE CASCADE,"
                + "level_z          INTEGER NOT NULL,"
                + "anchor_start_x2  INTEGER NOT NULL,"
                + "anchor_start_y2  INTEGER NOT NULL,"
                + "anchor_end_x2    INTEGER NOT NULL,"
                + "anchor_end_y2    INTEGER NOT NULL,"
                + "door_state       TEXT NOT NULL,"
                + "CHECK(door_state IN ('OPEN','CLOSED')),"
                + "CHECK ("
                + "    (cluster_id IS NOT NULL AND corridor_id IS NULL)"
                + " OR (cluster_id IS NULL AND corridor_id IS NOT NULL)"
                + ")"
                + ")");
        stmt.execute("CREATE TABLE IF NOT EXISTS dungeon_door_segments ("
                + "door_id          INTEGER NOT NULL REFERENCES dungeon_doors(door_id) ON DELETE CASCADE,"
                + "start_x2         INTEGER NOT NULL,"
                + "start_y2         INTEGER NOT NULL,"
                + "end_x2           INTEGER NOT NULL,"
                + "end_y2           INTEGER NOT NULL,"
                + "PRIMARY KEY (door_id, start_x2, start_y2, end_x2, end_y2)"
                + ")");
        stmt.execute("CREATE TABLE IF NOT EXISTS dungeon_corridor_nodes ("
                + "corridor_node_id      INTEGER PRIMARY KEY,"
                + "corridor_id           INTEGER NOT NULL REFERENCES dungeon_corridors(corridor_id) ON DELETE CASCADE,"
                + "grid_x2               INTEGER NOT NULL,"
                + "grid_y2               INTEGER NOT NULL,"
                + "door_id               INTEGER REFERENCES dungeon_doors(door_id),"
                + "UNIQUE(corridor_id, corridor_node_id),"
                + "UNIQUE(corridor_id, grid_x2, grid_y2),"
                + "UNIQUE(corridor_id, door_id)"
                + ")");
        stmt.execute("CREATE TABLE IF NOT EXISTS dungeon_corridor_segments ("
                + "corridor_segment_id   INTEGER PRIMARY KEY,"
                + "corridor_id           INTEGER NOT NULL REFERENCES dungeon_corridors(corridor_id) ON DELETE CASCADE,"
                + "start_node_id         INTEGER NOT NULL,"
                + "end_node_id           INTEGER NOT NULL,"
                + "CHECK(start_node_id < end_node_id),"
                + "UNIQUE(corridor_id, start_node_id, end_node_id),"
                + "FOREIGN KEY(corridor_id, start_node_id) REFERENCES dungeon_corridor_nodes(corridor_id, corridor_node_id) ON DELETE CASCADE,"
                + "FOREIGN KEY(corridor_id, end_node_id) REFERENCES dungeon_corridor_nodes(corridor_id, corridor_node_id) ON DELETE CASCADE"
                + ")");
        stmt.execute("CREATE TABLE IF NOT EXISTS dungeon_room_levels ("
                + "room_id          INTEGER NOT NULL REFERENCES dungeon_rooms(room_id) ON DELETE CASCADE,"
                + "level_z          INTEGER NOT NULL,"
                + "anchor_x2        INTEGER NOT NULL,"
                + "anchor_y2        INTEGER NOT NULL,"
                + "PRIMARY KEY (room_id, level_z)"
                + ")");
        stmt.execute("CREATE TABLE IF NOT EXISTS dungeon_room_cluster_levels ("
                + "cluster_id       INTEGER NOT NULL REFERENCES dungeon_room_clusters(cluster_id) ON DELETE CASCADE,"
                + "level_z          INTEGER NOT NULL,"
                + "anchor_x2        INTEGER NOT NULL,"
                + "anchor_y2        INTEGER NOT NULL,"
                + "PRIMARY KEY (cluster_id, level_z)"
                + ")");
        stmt.execute("CREATE TABLE IF NOT EXISTS dungeon_room_cluster_level_surface_cells ("
                + "cluster_id       INTEGER NOT NULL,"
                + "level_z          INTEGER NOT NULL,"
                + "cell_x2          INTEGER NOT NULL,"
                + "cell_y2          INTEGER NOT NULL,"
                + "PRIMARY KEY (cluster_id, level_z, cell_x2, cell_y2),"
                + "FOREIGN KEY(cluster_id, level_z) REFERENCES dungeon_room_cluster_levels(cluster_id, level_z) ON DELETE CASCADE"
                + ")");
        stmt.execute("CREATE TABLE IF NOT EXISTS dungeon_room_cluster_level_segments ("
                + "cluster_id       INTEGER NOT NULL,"
                + "level_z          INTEGER NOT NULL,"
                + "start_x2         INTEGER NOT NULL,"
                + "start_y2         INTEGER NOT NULL,"
                + "end_x2           INTEGER NOT NULL,"
                + "end_y2           INTEGER NOT NULL,"
                + "PRIMARY KEY (cluster_id, level_z, start_x2, start_y2, end_x2, end_y2),"
                + "FOREIGN KEY(cluster_id, level_z) REFERENCES dungeon_room_cluster_levels(cluster_id, level_z) ON DELETE CASCADE"
                + ")");
        stmt.execute("CREATE TABLE IF NOT EXISTS dungeon_room_cluster_level_floor_cells ("
                + "cluster_id       INTEGER NOT NULL,"
                + "level_z          INTEGER NOT NULL,"
                + "cell_x2          INTEGER NOT NULL,"
                + "cell_y2          INTEGER NOT NULL,"
                + "PRIMARY KEY (cluster_id, level_z, cell_x2, cell_y2),"
                + "FOREIGN KEY(cluster_id, level_z) REFERENCES dungeon_room_cluster_levels(cluster_id, level_z) ON DELETE CASCADE"
                + ")");
        stmt.execute("CREATE TABLE IF NOT EXISTS dungeon_cluster_walls ("
                + "wall_id          INTEGER PRIMARY KEY,"
                + "cluster_id       INTEGER NOT NULL REFERENCES dungeon_room_clusters(cluster_id) ON DELETE CASCADE,"
                + "level_z          INTEGER NOT NULL,"
                + "wall_kind_id     INTEGER NOT NULL REFERENCES dungeon_wall_kinds(wall_kind_id),"
                + "anchor_start_x2  INTEGER NOT NULL,"
                + "anchor_start_y2  INTEGER NOT NULL,"
                + "anchor_end_x2    INTEGER NOT NULL,"
                + "anchor_end_y2    INTEGER NOT NULL"
                + ")");
        stmt.execute("CREATE TABLE IF NOT EXISTS dungeon_cluster_wall_segments ("
                + "wall_id          INTEGER NOT NULL REFERENCES dungeon_cluster_walls(wall_id) ON DELETE CASCADE,"
                + "start_x2         INTEGER NOT NULL,"
                + "start_y2         INTEGER NOT NULL,"
                + "end_x2           INTEGER NOT NULL,"
                + "end_y2           INTEGER NOT NULL,"
                + "PRIMARY KEY (wall_id, start_x2, start_y2, end_x2, end_y2)"
                + ")");
        stmt.execute("CREATE TABLE IF NOT EXISTS dungeon_room_exit_descriptions ("
                + "room_id          INTEGER NOT NULL REFERENCES dungeon_rooms(room_id) ON DELETE CASCADE,"
                + "level_z          INTEGER NOT NULL DEFAULT 0,"
                + "cell_x           INTEGER NOT NULL,"
                + "cell_y           INTEGER NOT NULL,"
                + "edge_direction   TEXT NOT NULL,"
                + "description      TEXT,"
                + "sort_order       INTEGER NOT NULL DEFAULT 0,"
                + "PRIMARY KEY (room_id, level_z, cell_x, cell_y, edge_direction)"
                + ")");
        stmt.execute("CREATE TABLE IF NOT EXISTS dungeon_stairs ("
                + "stair_id         INTEGER PRIMARY KEY AUTOINCREMENT,"
                + "dungeon_map_id   INTEGER NOT NULL REFERENCES dungeon_maps(dungeon_map_id) ON DELETE CASCADE,"
                + "name             TEXT,"
                + "anchor_cell_x    INTEGER NOT NULL,"
                + "anchor_cell_y    INTEGER NOT NULL,"
                + "anchor_level_z   INTEGER NOT NULL,"
                + "shape_kind       TEXT NOT NULL,"
                + "shape_direction_code INTEGER NOT NULL DEFAULT 0,"
                + "shape_param1     INTEGER NOT NULL DEFAULT 0,"
                + "shape_param2     INTEGER NOT NULL DEFAULT 0,"
                + "min_level_z      INTEGER NOT NULL,"
                + "max_level_z      INTEGER NOT NULL,"
                + "CHECK(shape_kind IN ('STACK','LINE','SQUARE','RECTANGLE','CIRCLE'))"
                + ")");
        // Ordered path nodes are the canonical persisted stair geometry.
        // Exits are intentionally absent from the schema and must be re-derived from the path plus authored stop levels.
        stmt.execute("CREATE TABLE IF NOT EXISTS dungeon_stair_path_nodes ("
                + "stair_id         INTEGER NOT NULL REFERENCES dungeon_stairs(stair_id) ON DELETE CASCADE,"
                + "sort_order       INTEGER NOT NULL,"
                + "cell_x           INTEGER NOT NULL,"
                + "cell_y           INTEGER NOT NULL,"
                + "cell_z           INTEGER NOT NULL,"
                + "PRIMARY KEY (stair_id, sort_order)"
                + ")");
        stmt.execute("CREATE TABLE IF NOT EXISTS dungeon_stair_stop_levels ("
                + "stair_id         INTEGER NOT NULL REFERENCES dungeon_stairs(stair_id) ON DELETE CASCADE,"
                + "level_z          INTEGER NOT NULL,"
                + "PRIMARY KEY (stair_id, level_z)"
                + ")");
        stmt.execute("CREATE TABLE IF NOT EXISTS dungeon_transition_stair_path_nodes ("
                + "transition_id     INTEGER NOT NULL REFERENCES dungeon_transitions(transition_id) ON DELETE CASCADE,"
                + "sort_order        INTEGER NOT NULL,"
                + "cell_x            INTEGER NOT NULL,"
                + "cell_y            INTEGER NOT NULL,"
                + "cell_z            INTEGER NOT NULL,"
                + "PRIMARY KEY (transition_id, sort_order)"
                + ")");
        stmt.execute("CREATE TABLE IF NOT EXISTS dungeon_transition_stair_stop_levels ("
                + "transition_id     INTEGER NOT NULL REFERENCES dungeon_transitions(transition_id) ON DELETE CASCADE,"
                + "level_z           INTEGER NOT NULL,"
                + "PRIMARY KEY (transition_id, level_z)"
                + ")");
        stmt.execute("CREATE TABLE IF NOT EXISTS dungeon_transitions ("
                + "transition_id            INTEGER PRIMARY KEY AUTOINCREMENT,"
                + "dungeon_map_id           INTEGER NOT NULL REFERENCES dungeon_maps(dungeon_map_id) ON DELETE CASCADE,"
                + "description              TEXT,"
                + "placement_type           TEXT,"
                + "door_id                  INTEGER REFERENCES dungeon_doors(door_id),"
                + "stair_anchor_cell_x      INTEGER,"
                + "stair_anchor_cell_y      INTEGER,"
                + "stair_anchor_level_z     INTEGER,"
                + "stair_shape_kind         TEXT,"
                + "stair_shape_direction_code INTEGER,"
                + "stair_shape_param1       INTEGER,"
                + "stair_shape_param2       INTEGER,"
                + "stair_min_level_z        INTEGER,"
                + "stair_max_level_z        INTEGER,"
                + "destination_type         TEXT NOT NULL,"
                + "target_overworld_map_id  INTEGER REFERENCES hex_maps(map_id) ON DELETE SET NULL,"
                + "target_overworld_tile_id INTEGER REFERENCES hex_tiles(tile_id) ON DELETE SET NULL,"
                + "target_dungeon_map_id    INTEGER REFERENCES dungeon_maps(dungeon_map_id) ON DELETE SET NULL,"
                + "target_transition_id     INTEGER REFERENCES dungeon_transitions(transition_id) ON DELETE SET NULL,"
                + "linked_transition_id     INTEGER REFERENCES dungeon_transitions(transition_id) ON DELETE SET NULL"
                + ")");
    }
}
