/**
 * Render Primitives
 *
 * Shape-agnostic types for rendering. Used by utils/render.ts.
 * Can be generated by hex-mapper, square-mapper, or any other mapper.
 *
 * @module schemas/geometry/render
 */

// ============================================================================
// Primitives
// ============================================================================

/**
 * Polygon primitive for SVG rendering.
 * Shape-agnostic: works for hex, square, or any polygon.
 */
export type PolygonPrimitive = {
    points: string;          // SVG points string (e.g., "0,0 10,0 10,10")
    fill: string;            // CSS color
    stroke?: string;
    strokeWidth?: number;
};

/**
 * Text primitive for labels.
 */
export type TextPrimitive = {
    x: number;
    y: number;
    text: string;
    fill?: string;
    fontSize?: number;
    anchor?: 'start' | 'middle' | 'end';
};

// ============================================================================
// Batch
// ============================================================================

/**
 * A batch of primitives to render.
 */
export type RenderBatch = {
    width: number;
    height: number;
    polygons: PolygonPrimitive[];
    labels?: TextPrimitive[];
};
