package src.domain.dungeon.published;

public enum DungeonEditorTool {
    SELECT,
    ROOM_PAINT,
    ROOM_DELETE,
    WALL_CREATE,
    WALL_DELETE,
    DOOR_CREATE,
    DOOR_DELETE,
    CORRIDOR_CREATE,
    CORRIDOR_DELETE,
    STAIR_CREATE,
    STAIR_CREATE_SQUARE,
    STAIR_CREATE_CIRCULAR,
    STAIR_DELETE,
    TRANSITION_CREATE,
    TRANSITION_DELETE
}
