/**
 * Tile Domain Types
 *
 * Shared tile data structure used across map features.
 * This is the core data model for hex tiles.
 *
 * @module services/domain/tile-types
 */

import type { TerrainType, FloraType, MoistureLevel } from "./terrain-types";

/**
 * Source of a derived tile property.
 * - 'auto': Generated by simulation (e.g., climate service, terrain analyzer)
 * - 'manual': Set by user (protected from auto-overwrite)
 */
export type DerivationSource = 'auto' | 'manual';

/**
 * Icon-Based Tile Data
 *
 * Terrain representation using dual-layer icons (Terrain + Flora).
 * This is the canonical tile data structure shared across:
 * - Cartographer (editing)
 * - Session Runner (travel/encounters)
 * - Climate system (weather/temperature)
 */
export type TileData = {
    terrain?: TerrainType;        // Physical ground type: "plains" | "hills" | "mountains"
    flora?: FloraType;            // Vegetation coverage: "dense" | "medium" | "field" | "barren"
    backgroundColor?: string;     // Optional colored hex fill (e.g., "#2e7d32")
    region?: string;              // Region assignment
    faction?: string;             // Faction ownership
    manualFactionEdit?: boolean;  // Flag: User manually edited faction (simulation should not override)
    note?: string;                // Body text notes
    locationMarker?: string;      // POI marker reference
    elevation?: number;           // Height in meters above sea level (-100 to +5000)
    moisture?: MoistureLevel;     // Moisture level: "desert" | "dry" | "lush" | etc.
    groundwater?: number;         // Groundwater saturation level: 0-100 (dry to saturated)
    fertility?: number;           // Soil fertility: 0-100 (barren to rich)

    // Symbol variants (for visual variation in multi-symbol distribution)
    terrainVariants?: number[];   // Variant indices for each terrain symbol (e.g., [1, 3, 2] for 3 mountain symbols)
    floraVariants?: number[];     // Variant indices for each flora symbol (e.g., [2, 1, 4, 2, 3] for 5 tree symbols)

    // Climate parameters (optional per-hex weather modifiers)
    climate?: {
        temperatureOffset?: number;  // User-painted temperature offset (Celsius, -30 to +30)
    };

    // Derivation tracking (which properties were auto-generated vs. manually set)
    derivations?: {
        moisture?: { source: DerivationSource };
        flora?: { source: DerivationSource };
        terrain?: { source: DerivationSource };
    };
};
