package saltmarcher.architecture.documentation;

import java.util.List;
import java.util.Map;
import saltmarcher.architecture.documentation.support.MarkdownTableCoverageValidator;

public final class DocumentationCoverageCatalog {

    private static final Map<String, Specification> SPECIFICATIONS = Map.ofEntries(
            Map.entry("dataGateway", spec(
                    "docs/project/architecture/enforcement/data-gateway-enforcement.md",
                    "data-gateway-enforcement-coverage-complete",
                    "Data gateway enforcement document must exist.",
                    "Could not read data gateway enforcement document: ",
                    rows(
                            row("data-gateway-source-adapter-mechanics-ownership", "Review-Owned"),
                            row("data-gateway-no-generic-infrastructure-business-policy-or-runtime-composition", "Review-Owned"),
                            row("data-gateway-domain-independence", "Enforced",
                                    List.of("data-gateway bundle ArchUnit", "DataGatewayArchitectureTest"),
                                    List.of("./gradlew checkDataEnforcement")),
                            row("data-gateway-public-signature-boundary", "Enforced",
                                    List.of("data-gateway bundle Error Prone", "DataGatewayReturnTypeBoundary"),
                                    List.of("./gradlew compileJava", "./gradlew checkDataEnforcement")),
                            row("data-gateway-internal-data-collaborator-boundary", "Review-Owned")))),
            Map.entry("dataLayer", spec(
                    "docs/project/architecture/enforcement/data-layer-enforcement.md",
                    "data-layer-enforcement-coverage-complete",
                    "Data Layer enforcement coverage document is missing.",
                    "Could not read Data Layer enforcement coverage: ",
                    rows(
                            row("data-root-service-contribution-only", "Enforced",
                                    List.of("data-layer bundle build-harness", "DataLayerTopologyRules"),
                                    List.of("./gradlew checkDataEnforcement")),
                            row("data-feature-bucket-layout", "Enforced",
                                    List.of("data-layer bundle build-harness", "DataLayerTopologyRules"),
                                    List.of("./gradlew checkDataEnforcement")),
                            row("data-feature-composition-root-presence", "Enforced",
                                    List.of("data-layer bundle build-harness", "DataLayerTopologyRules"),
                                    List.of("./gradlew checkDataEnforcement")),
                            row("data-layer-adapter-zone-ownership", "Review-Owned"),
                            row("data-outer-layer-independence", "Enforced",
                                    List.of(
                                            "data-layer bundle ArchUnit",
                                            "dataMustNotReachBootstrapOrPresentation",
                                            "dataMustNotReachPresentationShellOrBootstrap"),
                                    List.of("./gradlew checkDataEnforcement")),
                            row("data-non-root-shell-independence", "Enforced",
                                    List.of("data-layer bundle ArchUnit", "dataMustNotReachPresentationShellOrBootstrap"),
                                    List.of("./gradlew checkDataEnforcement")),
                            row("data-foreign-feature-public-boundary", "Enforced",
                                    List.of("data-layer bundle ArchUnit", "dataFeaturesMustOnlyUseForeignFeatureApis"),
                                    List.of("./gradlew checkDataEnforcement")),
                            row("data-foreign-private-data-bucket-isolation", "Enforced",
                                    List.of("data-layer bundle ArchUnit", "dataFeaturesMustNotReachForeignPrivateDataBuckets"),
                                    List.of("./gradlew checkDataEnforcement")),
                            row("data-feature-cycles", "Enforced",
                                    List.of("data-layer bundle ArchUnit", "dataFeaturesMustStayCycleFree"),
                                    List.of("./gradlew checkDataEnforcement")),
                            row("data-layer-no-business-policy-or-second-model", "Review-Owned"),
                            row("data-layer-no-public-backend-boundary", "Review-Owned"),
                            row("data-service-registry-root-only", "Enforced",
                                    List.of(
                                            "data-layer bundle Error Prone",
                                            "ServiceRegistryRegistrationPlacement",
                                            "data-layer bundle build-harness",
                                            "DataLayerTopologyRules"),
                                    List.of("./gradlew compileJava", "./gradlew checkDataEnforcement")),
                            row("data-layer-shell-runtime-seam-only-through-root-service-registration", "Enforced Elsewhere",
                                    List.of(
                                            "data-service-registry-root-only",
                                            "data-service-contribution-shell-runtime-seam-subset",
                                            "data-non-root-shell-independence"),
                                    List.of("./gradlew compileJava")),
                            row("data-layer-domain-source-dependencies-only-through-own-feature-ports-and-foreign-public-boundaries", "Enforced Elsewhere",
                                    List.of(
                                            "data-service-contribution-register-export-shape",
                                            "data-repository-role-contract",
                                            "data-query-role-contract",
                                            "data-gateway-domain-independence",
                                            "data-foreign-feature-public-boundary"),
                                    List.of("./gradlew compileJava")),
                            row("data-layer-root-runtime-export-surface-only", "Review-Owned")))),
            Map.entry("dataMapper", spec(
                    "docs/project/architecture/enforcement/data-mapper-enforcement.md",
                    "data-mapper-enforcement-coverage-complete",
                    "Data mapper enforcement document must exist.",
                    "Could not read data mapper enforcement document: ",
                    rows(
                            row("data-mapper-non-trivial-translation-ownership", "Review-Owned"),
                            row("data-mapper-translation-surface-ownership", "Review-Owned"),
                            row("data-mapper-no-source-mechanics", "Source-Pattern Enforced",
                                    List.of("data-mapper bundle PMD", "DataMapperSourceMechanicsRule"),
                                    List.of("./gradlew checkDataEnforcement")),
                            row("data-mapper-no-business-rules-or-policy", "Review-Owned"),
                            row("data-mapper-shape-translation-boundary", "Review-Owned")))),
            Map.entry("dataModel", spec(
                    "docs/project/architecture/enforcement/data-model-enforcement.md",
                    "data-model-enforcement-coverage-complete",
                    "Data Model enforcement coverage document is missing.",
                    "Could not read Data Model enforcement coverage: ",
                    rows(
                            row("data-feature-schema-contract", "Enforced",
                                    List.of("data-model bundle build-harness", "DataModelTopologyRules"),
                                    List.of("./gradlew checkDataEnforcement")),
                            row("data-schema-ddl-placement", "Source-Pattern Enforced",
                                    List.of("data-model bundle PMD", "DataModelSchemaDdlPlacementRule"),
                                    List.of("./gradlew checkDataEnforcement")),
                            row("data-model-source-shape", "Enforced",
                                    List.of("data-model bundle Error Prone", "DataModelSourceShape"),
                                    List.of("./gradlew compileJava", "./gradlew checkDataEnforcement")),
                            row("data-model-domain-independence", "Enforced",
                                    List.of("data-model bundle ArchUnit", "DataModelArchitectureTest"),
                                    List.of("./gradlew checkDataEnforcement")),
                            row("data-model-source-local-not-renamed-domain-entities", "Review-Owned"),
                            row("data-model-public-signature-boundary", "Enforced",
                                    List.of("data-model bundle Error Prone", "DataModelSourceShape"),
                                    List.of("./gradlew compileJava", "./gradlew checkDataEnforcement")),
                            row("data-schema-table-name-owned-by-schema", "Enforced",
                                    List.of("data-model bundle build-harness", "DataModelTopologyRules"),
                                    List.of("./gradlew checkDataEnforcement")),
                            row("data-model-field-name-centralization", "Review-Owned")))),
            Map.entry("dataPersistencecore", spec(
                    "docs/project/architecture/enforcement/data-persistencecore-enforcement.md",
                    "data-persistencecore-enforcement-coverage-complete",
                    "Data Persistencecore enforcement document is missing.",
                    "Could not read data persistencecore enforcement document: ",
                    rows(
                            row("data-persistencecore-model-generic-schema-helper-semantics", "Review-Owned"),
                            row("data-persistencecore-sqlite-generic-infrastructure-semantics", "Review-Owned"),
                            row("data-persistencecore-no-feature-specific-data-dependencies", "Enforced",
                                    List.of(
                                            "data-persistencecore bundle ArchUnit",
                                            "persistencecoreMustStayIndependentFromFeatureSpecificDataPackages"),
                                    List.of("./gradlew checkDataEnforcement")),
                            row("data-persistencecore-no-domain-dependencies", "Enforced",
                                    List.of(
                                            "data-persistencecore bundle ArchUnit",
                                            "persistencecoreMustNotDependOnDomainTypes"),
                                    List.of("./gradlew checkDataEnforcement")),
                            row("data-persistencecore-model-data-internal-consumer-boundary", "Review-Owned"),
                            row("data-persistencecore-sqlite-data-internal-consumer-boundary", "Review-Owned")))),
            Map.entry("dataQuery", spec(
                    "docs/project/architecture/enforcement/data-query-enforcement.md",
                    "data-query-enforcement-coverage-complete",
                    "Data query enforcement document must exist.",
                    "Could not read data query enforcement document: ",
                    rows(
                            row("data-query-separate-read-adapter-necessity", "Review-Owned"),
                            row("data-query-role-contract", "Enforced",
                                    List.of("data-query bundle Error Prone", "DataQueryRoleContract"),
                                    List.of("./gradlew compileJava", "./gradlew checkDataEnforcement")),
                            row("data-query-no-source-mechanics", "Review-Owned"),
                            row("data-query-no-public-non-adapter-boundary-types", "Enforced",
                                    List.of("data-query bundle Error Prone", "DataQueryRoleContract"),
                                    List.of("./gradlew compileJava", "./gradlew checkDataEnforcement")),
                            row("data-query-read-only-source-shape", "Enforced",
                                    List.of("data-query bundle Error Prone", "DataQueryGatewayMutationBoundary"),
                                    List.of("./gradlew compileJava", "./gradlew checkDataEnforcement")),
                            row("data-query-read-only-role-semantics", "Review-Owned"),
                            row("data-query-public-port-surface-only", "Enforced",
                                    List.of("data-query bundle Error Prone", "DataQueryRoleContract"),
                                    List.of("./gradlew compileJava", "./gradlew checkDataEnforcement")),
                            row("data-query-public-signature-boundary", "Enforced",
                                    List.of("data-query bundle Error Prone", "DataQueryPublicSignatureBoundary"),
                                    List.of("./gradlew compileJava", "./gradlew checkDataEnforcement")),
                            row("data-query-no-foreign-published-reply-channel-roundtrip", "Enforced",
                                    List.of("data-query bundle Error Prone", "DataQueryForeignPublishedReplyChannelRoundTrip"),
                                    List.of("./gradlew compileJava", "./gradlew checkDataEnforcement")),
                            row("data-query-no-overbroad-foreign-published-payload-surface", "Enforced",
                                    List.of("data-query bundle build-harness", "DataQueryForeignPublishedPayloadSurfaceRules"),
                                    List.of("./gradlew checkDataEnforcement")),
                            row("data-query-gateway-collaborator-boundary", "Enforced",
                                    List.of("data-query bundle Error Prone", "DataQueryGatewayCollaboratorBoundary"),
                                    List.of("./gradlew compileJava", "./gradlew checkDataEnforcement")),
                            row("data-query-foreign-published-carrier-thinning-candidate", "Candidate")))),
            Map.entry("dataRepository", spec(
                    "docs/project/architecture/enforcement/data-repository-enforcement.md",
                    "data-repository-enforcement-coverage-complete",
                    "Data repository enforcement document must exist.",
                    "Could not read data repository enforcement document: ",
                    rows(
                            row("data-repository-role-contract", "Enforced",
                                    List.of("data-repository bundle Error Prone", "DataRepositoryRoleContract"),
                                    List.of("./gradlew compileJava", "./gradlew checkDataEnforcement")),
                            row("data-repository-no-public-non-adapter-boundary-types", "Enforced",
                                    List.of("data-repository bundle Error Prone", "DataRepositoryRoleContract"),
                                    List.of("./gradlew compileJava", "./gradlew checkDataEnforcement")),
                            row("data-repository-no-source-mechanics", "Source-Pattern Enforced",
                                    List.of("data-repository bundle PMD", "DataRepositorySourceMechanicsRule"),
                                    List.of("./gradlew checkDataEnforcement")),
                            row("data-repository-write-model-role-semantics", "Review-Owned"),
                            row("data-repository-public-port-surface-only", "Enforced",
                                    List.of("data-repository bundle Error Prone", "DataRepositoryRoleContract"),
                                    List.of("./gradlew compileJava", "./gradlew checkDataEnforcement")),
                            row("data-repository-public-signature-boundary", "Enforced",
                                    List.of("data-repository bundle Error Prone", "DataRepositoryPublicSignatureBoundary"),
                                    List.of("./gradlew compileJava", "./gradlew checkDataEnforcement")),
                            row("data-repository-gateway-collaborator-boundary", "Enforced",
                                    List.of("data-repository bundle Error Prone", "DataRepositoryGatewayCollaboratorBoundary"),
                                    List.of("./gradlew compileJava", "./gradlew checkDataEnforcement"))))),
            Map.entry("dataServiceContribution", spec(
                    "docs/project/architecture/enforcement/data-service-contribution-enforcement.md",
                    "data-enforcement-coverage-complete",
                    "Data ServiceContribution enforcement document must exist.",
                    "Could not read data ServiceContribution enforcement coverage: ",
                    rows(
                            row("data-service-contribution-discovery-entrypoint-shape", "Review-Owned"),
                            row("data-service-contribution-stateless-public-surface", "Review-Owned"),
                            row("data-service-contribution-no-source-mechanics", "Review-Owned"),
                            row("data-service-contribution-construction-purity", "Enforced",
                                    List.of("data-service-contribution bundle Error Prone", "DataServiceContributionConstructionPurity"),
                                    List.of("./gradlew compileJava", "./gradlew checkDataEnforcement")),
                            row("data-service-contribution-no-hidden-business-or-runtime-workflow", "Review-Owned"),
                            row("data-service-contribution-shell-runtime-seam-subset", "Enforced",
                                    List.of("data-service-contribution bundle Error Prone", "DataServiceContributionShellApiAllowlist"),
                                    List.of("./gradlew compileJava", "./gradlew checkDataEnforcement")),
                            row("data-service-contribution-register-export-shape", "Enforced",
                                    List.of("data-service-contribution bundle Error Prone", "DataServiceContributionRegisterExportShape"),
                                    List.of("./gradlew compileJava", "./gradlew checkDataEnforcement")),
                            row("data-service-contribution-factory-export-shape", "Enforced",
                                    List.of("data-service-contribution bundle Error Prone", "DataServiceContributionRegisterExportShape"),
                                    List.of("./gradlew compileJava", "./gradlew checkDataEnforcement")),
                            row("data-service-contribution-composition-collaborator-assembly-only", "Review-Owned")))),
            Map.entry("domainApplicationService", spec(
                    "docs/project/architecture/enforcement/domain-application-service-enforcement.md",
                    "domain-enforcement-coverage-complete",
                    "Domain ApplicationService enforcement coverage document is missing.",
                    "Could not read Domain ApplicationService enforcement coverage: ",
                    rows(
                            row("domain-applicationservice-root-presence", "Enforced",
                                    List.of(
                                            "domain-application-service bundle build-harness",
                                            "DomainApplicationServiceTopologyRules",
                                            "DomainApplicationServiceDocumentationRules"),
                                    List.of("./gradlew checkDomainEnforcement")),
                            row("domain-applicationservice-class-shape", "Enforced",
                                    List.of("domain-application-service bundle Error Prone", "DomainApplicationServiceApiShape"),
                                    List.of("./gradlew compileJava", "./gradlew checkDomainEnforcement")),
                            row("domain-applicationservice-public-input-carriers", "Enforced",
                                    List.of("domain-application-service bundle Error Prone", "DomainApplicationServiceApiShape"),
                                    List.of("./gradlew compileJava", "./gradlew checkDomainEnforcement")),
                            row("domain-applicationservice-command-no-direct-return", "Enforced",
                                    List.of("domain-application-service bundle Error Prone", "DomainApplicationServiceApiShape"),
                                    List.of("./gradlew compileJava", "./gradlew checkDomainEnforcement")),
                            row("domain-applicationservice-no-nested-contracts", "Enforced",
                                    List.of("domain-application-service bundle Error Prone", "DomainApplicationServiceApiShape"),
                                    List.of("./gradlew compileJava", "./gradlew checkDomainEnforcement")),
                            row("domain-applicationservice-role-reference-boundary", "Enforced",
                                    List.of("domain-application-service bundle Error Prone", "DomainApplicationServiceRoleBoundary"),
                                    List.of("./gradlew compileJava", "./gradlew checkDomainEnforcement")),
                            row("domain-applicationservice-thin-router-one-usecase-call", "Enforced",
                                    List.of("domain-application-service bundle Error Prone", "DomainApplicationServiceThinRouter"),
                                    List.of("./gradlew compileJava", "./gradlew checkDomainEnforcement")),
                            row("domain-applicationservice-no-model-mutation-translation", "Enforced",
                                    List.of("domain-application-service bundle Error Prone", "DomainApplicationServiceThinRouter"),
                                    List.of("./gradlew compileJava", "./gradlew checkDomainEnforcement")),
                            row("domain-applicationservice-no-direct-infrastructure-construction-source-pattern", "Review-Owned"),
                            row("domain-applicationservice-constructor-composition-boundary", "Review-Owned"),
                            row("domain-applicationservice-public-boundary-signature-purity", "Enforced",
                                    List.of("domain-application-service bundle Error Prone", "DomainPublicBoundarySignaturePurity"),
                                    List.of("./gradlew compileJava", "./gradlew checkDomainEnforcement")),
                            row("domain-applicationservice-public-carrier-translation-boundary", "Enforced Elsewhere",
                                    List.of(
                                            "domain-usecase bundle Error Prone",
                                            "DomainApplicationNoSameContextPublishedDependency",
                                            "domain-layer bundle Error Prone",
                                            "DomainModuleNoPublishedCarrierDependency"),
                                    List.of("./gradlew compileJava", "./gradlew checkDomainEnforcement")),
                            row("domain-applicationservice-no-runtime-composition-ownership", "Review-Owned"),
                            row("domain-applicationservice-no-business-policy-ownership", "Review-Owned")))),
            Map.entry("domainConstants", spec(
                    "docs/project/architecture/enforcement/domain-constants-enforcement.md",
                    "domain-constants-enforcement-coverage-complete",
                    "Domain constants enforcement document must exist.",
                    "Could not read domain constants enforcement document: ",
                    rows(
                            row("domain-constants-direct-file-placement", "Enforced",
                                    List.of("domain-constants bundle build-harness", "DomainConstantsTopologyRules"),
                                    List.of("./gradlew checkDomainEnforcement")),
                            row("domain-constants-role-shape", "Enforced",
                                    List.of("domain-constants bundle build-harness", "DomainConstantsTopologyRules"),
                                    List.of("./gradlew checkDomainEnforcement")),
                            row("domain-constants-immutable-only", "Review-Owned"),
                            row("domain-constants-no-runtime-or-state-ownership", "Review-Owned"),
                            row("domain-constants-constants-only-dependency-boundary", "Enforced",
                                    List.of("domain-constants bundle Error Prone", "DomainConstantsRoleBoundary"),
                                    List.of("./gradlew checkDomainEnforcement"))))),
            Map.entry("domainContext", spec(
                    "docs/project/architecture/enforcement/domain-context-enforcement.md",
                    "domain-context-enforcement-coverage-complete",
                    "Domain context enforcement document must exist.",
                    "Could not read domain context enforcement document: ",
                    rows(
                            row("domain-context-document-presence", "Enforced",
                                    List.of("domain-context-enforcement", "DomainContextDocumentationRules"),
                                    List.of("./gradlew checkDomainEnforcement")),
                            row("domain-context-name-marker", "Enforced",
                                    List.of("domain-context-enforcement", "DomainContextDocumentationRules"),
                                    List.of("./gradlew checkDomainEnforcement")),
                            row("domain-context-role-marker", "Enforced",
                                    List.of("domain-context-enforcement", "DomainContextDocumentationRules"),
                                    List.of("./gradlew checkDomainEnforcement")),
                            row("domain-context-standard-role-coverage", "Enforced",
                                    List.of("domain-context-enforcement", "DomainContextDocumentationRules"),
                                    List.of("./gradlew checkDomainEnforcement")),
                            row("domain-context-base-sections", "Enforced",
                                    List.of("domain-context-enforcement", "DomainContextDocumentationRules"),
                                    List.of("./gradlew checkDomainEnforcement")),
                            row("domain-context-application-service-marker", "Enforced",
                                    List.of("domain-context-enforcement", "DomainContextDocumentationRules"),
                                    List.of("./gradlew checkDomainEnforcement")),
                            row("domain-context-authored-truth-required-sections", "Enforced",
                                    List.of("domain-context-enforcement", "DomainContextDocumentationRules"),
                                    List.of("./gradlew checkDomainEnforcement")),
                            row("domain-context-aggregate-root-marker-shape", "Enforced",
                                    List.of("domain-context-enforcement", "DomainContextDocumentationRules"),
                                    List.of("./gradlew checkDomainEnforcement")),
                            row("domain-context-generation-policy-required-sections", "Enforced",
                                    List.of("domain-context-enforcement", "DomainContextDocumentationRules"),
                                    List.of("./gradlew checkDomainEnforcement")),
                            row("domain-context-generation-policy-write-model-none", "Enforced",
                                    List.of("domain-context-enforcement", "DomainContextDocumentationRules"),
                                    List.of("./gradlew checkDomainEnforcement")),
                            row("domain-context-generation-policy-ephemeral-rationale", "Enforced",
                                    List.of("domain-context-enforcement", "DomainContextDocumentationRules"),
                                    List.of("./gradlew checkDomainEnforcement")),
                            row("domain-context-party-owned-truth", "Review-Owned"),
                            row("domain-context-creatures-owned-reference-scope", "Review-Owned"),
                            row("domain-context-encounter-owned-roster-truth", "Review-Owned"),
                            row("domain-context-encountertable-owned-reference-scope", "Review-Owned"),
                            row("domain-context-dungeon-owned-world-space-truth", "Review-Owned"),
                            row("domain-context-sessionplanner-owned-session-record-truth", "Review-Owned"),
                            row("domain-context-authored-truth-write-model-required", "Enforced",
                                    List.of("domain-context-enforcement", "DomainContextDocumentationRules"),
                                    List.of("./gradlew checkDomainEnforcement")),
                            row("domain-context-creatures-no-encounter-or-lifecycle-truth", "Review-Owned"),
                            row("domain-context-encounter-no-foreign-truth-ownership", "Review-Owned"),
                            row("domain-context-encountertable-no-creature-or-generation-policy-truth", "Review-Owned"),
                            row("domain-context-sessionplanner-no-foreign-truth-ownership", "Review-Owned"),
                            row("domain-context-standard-relationship-coverage", "Enforced",
                                    List.of("domain-context-enforcement", "DomainContextDocumentationRules"),
                                    List.of("./gradlew checkDomainEnforcement")),
                            row("domain-context-party-publishes-downstream-facts", "Review-Owned"),
                            row("domain-context-creatures-publishes-policy-input-facts", "Review-Owned"),
                            row("domain-context-encounter-consumes-foreign-public-boundaries", "Review-Owned"),
                            row("domain-context-encountertable-data-adapter-ingest-and-public-export", "Review-Owned"),
                            row("domain-context-dungeon-no-domain-relationship-to-other-active-contexts", "Review-Owned"),
                            row("domain-context-sessionplanner-consumes-party-and-encounter-public-boundaries", "Review-Owned")))),
            Map.entry("domainHelper", spec(
                    "docs/project/architecture/enforcement/domain-helper-enforcement.md",
                    "domain-helper-enforcement-coverage-complete",
                    "Domain helper enforcement document must exist.",
                    "Could not read domain helper enforcement document: ",
                    rows(
                            row("domain-helper-direct-file-placement", "Enforced",
                                    List.of("domain-helper bundle build-harness", "DomainHelperTopologyRules"),
                                    List.of("./gradlew checkDomainEnforcement")),
                            row("domain-helper-role-shape", "Enforced",
                                    List.of("domain-helper bundle build-harness", "DomainHelperTopologyRules"),
                                    List.of("./gradlew checkDomainEnforcement")),
                            row("domain-helper-explicit-work-step", "Review-Owned"),
                            row("domain-helper-no-current-context-access", "Review-Owned"),
                            row("domain-helper-constants-only-downward-dependency", "Enforced",
                                    List.of("domain-helper bundle Error Prone", "DomainHelperRoleBoundary"),
                                    List.of("./gradlew checkDomainEnforcement"))))),
            Map.entry("domainLayer", spec(
                    "docs/project/architecture/enforcement/domain-layer-enforcement.md",
                    "domain-enforcement-coverage-complete",
                    "Domain Layer enforcement coverage document is missing.",
                    "Could not read Domain Layer enforcement coverage: ",
                    rows(
                            row("domain-layer-context-root-boundary-and-module-topology", "Enforced Elsewhere",
                                    List.of(
                                            "domain-applicationservice-root-presence",
                                            "domain-usecase-direct-file-placement",
                                            "domain-layer-forbidden-top-level-domain-buckets"),
                                    List.of("./gradlew checkDomainEnforcement", "./gradlew checkDocumentationEnforcement")),
                            row("domain-layer-root-direct-file-role-allowlist", "Enforced",
                                    List.of(
                                            "domain-layer bundle build-harness",
                                            "DomainLayerTopologyRules",
                                            "domain-layer bundle Error Prone",
                                            "DomainSourceTopologyPerimeter"),
                                    List.of("./gradlew compileJava", "./gradlew checkDomainEnforcement")),
                            row("domain-layer-model-root-family-directories-only", "Enforced",
                                    List.of("domain-layer bundle build-harness", "DomainLayerTopologyRules"),
                                    List.of("./gradlew checkDomainEnforcement")),
                            row("domain-layer-model-family-role-subpackage-required", "Enforced",
                                    List.of("domain-layer bundle build-harness", "DomainLayerTopologyRules"),
                                    List.of("./gradlew checkDomainEnforcement")),
                            row("domain-layer-model-role-package-name-allowlist", "Enforced",
                                    List.of("domain-layer bundle build-harness", "DomainLayerTopologyRules"),
                                    List.of("./gradlew checkDomainEnforcement")),
                            row("domain-layer-model-role-direct-file-placement", "Enforced",
                                    List.of("domain-layer bundle build-harness", "DomainLayerTopologyRules"),
                                    List.of("./gradlew checkDomainEnforcement")),
                            row("domain-layer-model-subtree-no-technical-buckets", "Enforced",
                                    List.of(
                                            "domain-layer bundle build-harness",
                                            "DomainLayerTopologyRules",
                                            "domain-layer bundle Error Prone",
                                            "DomainSourceTopologyPerimeter"),
                                    List.of("./gradlew compileJava", "./gradlew checkDomainEnforcement")),
                            row("domain-layer-forbidden-top-level-domain-buckets", "Enforced",
                                    List.of("domain-layer bundle build-harness", "DomainLayerTopologyRules"),
                                    List.of("./gradlew checkDomainEnforcement")),
                            row("domain-layer-reserved-role-suffix-perimeter", "Enforced",
                                    List.of(
                                            "domain-layer bundle build-harness",
                                            "DomainLayerTopologyRules",
                                            "domain-layer bundle Error Prone",
                                            "DomainSourceTopologyPerimeter"),
                                    List.of("./gradlew compileJava", "./gradlew checkDomainEnforcement")),
                            row("domain-layer-legacy-role-suffix-rejection", "Enforced",
                                    List.of(
                                            "domain-layer bundle build-harness",
                                            "DomainLayerTopologyRules",
                                            "domain-layer bundle Error Prone",
                                            "DomainSourceTopologyPerimeter"),
                                    List.of("./gradlew compileJava", "./gradlew checkDomainEnforcement")),
                            row("domain-layer-no-published-carrier-dependencies-inside-named-modules", "Enforced",
                                    List.of("domain-layer bundle Error Prone", "DomainModuleNoPublishedCarrierDependency"),
                                    List.of("./gradlew compileJava", "./gradlew checkDomainEnforcement")),
                            row("domain-layer-public-boundary-families-only", "Enforced Elsewhere",
                                    List.of(
                                            "domain-applicationservice-root-presence",
                                            "domain-applicationservice-public-input-carriers",
                                            "domain-applicationservice-command-no-direct-return",
                                            "domain-published-direct-file-placement",
                                            "domain-published-carrier-shape",
                                            "domain-published-read-model-handle-shape",
                                            "domain-port-role-shape",
                                            "domain-port-ownership-and-signature-boundary"),
                                    List.of(
                                            "./gradlew compileJava",
                                            "./gradlew checkDomainEnforcement",
                                            "./gradlew checkDocumentationEnforcement")),
                            row("domain-layer-no-outer-layer-or-infrastructure-dependencies", "Enforced",
                                    List.of(
                                            "domain-layer bundle ArchUnit",
                                            "domainMustStayIndependentFromOuterLayers",
                                            "domain-layer bundle Error Prone",
                                            "DomainForbiddenInfrastructureDependency"),
                                    List.of("./gradlew compileJava", "./gradlew checkDomainEnforcement")),
                            row("domain-layer-foreign-context-access-only-through-public-boundaries", "Enforced",
                                    List.of("domain-layer bundle ArchUnit", "domainFeaturesMustOnlyUseForeignFeatureApis"),
                                    List.of("./gradlew checkDomainEnforcement")),
                            row("domain-layer-internal-model-no-same-context-application-boundary-dependencies", "Enforced",
                                    List.of("domain-layer bundle ArchUnit", "domainInternalModelMustNotReachSameContextApplicationBoundary"),
                                    List.of("./gradlew checkDomainEnforcement")),
                            row("domain-layer-internal-model-no-port-or-repository-dependencies", "Enforced",
                                    List.of("domain-layer bundle ArchUnit", "domainInternalModelMustNotDependOnPortsOrRepositories"),
                                    List.of("./gradlew checkDomainEnforcement")),
                            row("domain-layer-core-business-ownership", "Review-Owned"),
                            row("domain-layer-no-ui-translation-or-runtime-composition-ownership", "Review-Owned"),
                            row("domain-layer-application-orchestration-only-outbound-calls", "Review-Owned"),
                            row("domain-layer-optional-role-package-necessity", "Review-Owned"),
                            row("domain-layer-technical-vocabulary-rejection", "Review-Owned")))),
            Map.entry("domainModel", spec(
                    "docs/project/architecture/enforcement/domain-model-enforcement.md",
                    "domain-model-enforcement-coverage-complete",
                    "Domain model enforcement document must exist.",
                    "Could not read domain model enforcement document: ",
                    rows(
                            row("domain-model-dynamic-state-ownership", "Enforced",
                                    List.of("domain-model bundle Error Prone", "DomainModelRoleBoundary"),
                                    List.of("./gradlew checkDomainEnforcement")),
                            row("domain-model-tree-placement", "Enforced",
                                    List.of("domain-model bundle build-harness", "DomainModelTopologyRules"),
                                    List.of("./gradlew checkDomainEnforcement")),
                            row("domain-model-state-semantic-adequacy", "Review-Owned"),
                            row("domain-model-no-outer-layer-dependencies", "Enforced Elsewhere",
                                    List.of(
                                            "domain-layer bundle ArchUnit", "domainMustStayIndependentFromOuterLayers",
                                            "domain-layer bundle Error Prone", "DomainForbiddenInfrastructureDependency"),
                                    List.of("./gradlew compileJava", "./gradlew checkDomainEnforcement")),
                            row("domain-model-published-derivation-ownership", "Review-Owned")))),
            Map.entry("domainPublished", spec(
                    "docs/project/architecture/enforcement/domain-published-enforcement.md",
                    "domain-enforcement-coverage-complete",
                    "Domain Published enforcement coverage document is missing.",
                    "Could not read Domain Published enforcement coverage: ",
                    rows(
                            row("domain-published-carrier-family-allowlist", "Review-Owned"),
                            row("domain-published-observable-state-handle-necessity", "Review-Owned"),
                            row("domain-published-direct-file-placement", "Enforced",
                                    List.of("domain-published bundle build-harness", "DomainPublishedTopologyRules"),
                                    List.of("./gradlew checkDomainEnforcement")),
                            row("domain-published-top-level-public-surface", "Enforced",
                                    List.of("domain-published bundle Error Prone", "DomainPublishedCarrierShape"),
                                    List.of("./gradlew compileJava", "./gradlew checkDomainEnforcement")),
                            row("domain-published-carrier-shape", "Enforced",
                                    List.of("domain-published bundle Error Prone", "DomainPublishedCarrierShape"),
                                    List.of("./gradlew compileJava", "./gradlew checkDomainEnforcement")),
                            row("domain-published-read-model-handle-shape", "Enforced",
                                    List.of("domain-published bundle Error Prone", "DomainPublishedReadModelShape"),
                                    List.of("./gradlew compileJava", "./gradlew checkDomainEnforcement")),
                            row("domain-published-no-callable-contracts", "Enforced",
                                    List.of("domain-published bundle build-harness", "DomainPublishedTopologyRules"),
                                    List.of("./gradlew checkDomainEnforcement")),
                            row("domain-published-nonmodel-passive-only", "Enforced",
                                    List.of("domain-published bundle Error Prone", "DomainPublishedReadModelShape"),
                                    List.of("./gradlew compileJava", "./gradlew checkDomainEnforcement")),
                            row("domain-published-domain-facts-only", "Review-Owned"),
                            row("domain-published-passive-boundary-language", "Review-Owned"),
                            row("domain-published-public-boundary-signature-purity", "Enforced",
                                    List.of("domain-published bundle Error Prone", "DomainPublishedBoundarySignaturePurity"),
                                    List.of("./gradlew compileJava", "./gradlew checkDomainEnforcement")),
                            row("domain-published-read-model-feedback-ownership", "Enforced Elsewhere",
                                    List.of(
                                            "domain-applicationservice-public-input-carriers",
                                            "domain-applicationservice-command-no-direct-return",
                                            "domain-usecase-no-same-context-published-dependencies",
                                            "view-layer-no-direct-applicationservice-result-to-viewstate-readback"),
                                    List.of(
                                            "./gradlew compileJava",
                                            "./gradlew checkDomainEnforcement",
                                            "./gradlew checkDomainEnforcement",
                                            "./gradlew checkViewEnforcement")),
                            row("domain-published-ubiquitous-language-stability", "Review-Owned")))),
            Map.entry("domainPort", spec(
                    "docs/project/architecture/enforcement/domain-port-enforcement.md",
                    "domain-port-enforcement-coverage-complete",
                    "Domain port enforcement document must exist.",
                    "Could not read domain port enforcement document: ",
                    rows(
                            row("domain-port-direct-file-placement", "Enforced",
                                    List.of("domain-port bundle build-harness", "DomainPortTopologyRules"),
                                    List.of("./gradlew checkDomainEnforcement")),
                            row("domain-port-role-shape", "Enforced",
                                    List.of("domain-port bundle build-harness", "DomainPortTopologyRules"),
                                    List.of("./gradlew checkDomainEnforcement")),
                            row("domain-port-no-foreign-mutation-or-data-seam", "Review-Owned"),
                            row("domain-port-ownership-and-signature-boundary", "Enforced",
                                    List.of("domain-port bundle Error Prone", "DomainPortRoleBoundary"),
                                    List.of("./gradlew checkDomainEnforcement")),
                            row("domain-port-published-listener-boundary", "Review-Owned"),
                            row("domain-port-domain-language", "Review-Owned")))),
            Map.entry("domainRepository", spec(
                    "docs/project/architecture/enforcement/domain-repository-enforcement.md",
                    "domain-repository-enforcement-coverage-complete",
                    "Domain repository enforcement document must exist.",
                    "Could not read domain repository enforcement document: ",
                    rows(
                            row("domain-repository-direct-file-placement", "Enforced",
                                    List.of("domain-repository bundle build-harness", "DomainRepositoryTopologyRules"),
                                    List.of("./gradlew checkDomainEnforcement")),
                            row("domain-repository-role-shape", "Enforced",
                                    List.of("domain-repository bundle build-harness", "DomainRepositoryTopologyRules"),
                                    List.of("./gradlew checkDomainEnforcement")),
                            row("domain-repository-outbound-trigger-ownership", "Review-Owned"),
                            row("domain-repository-no-src-data-type-leaks", "Review-Owned"),
                            row("domain-repository-no-same-context-published-state-channel", "Enforced",
                                    List.of("domain-repository bundle Error Prone", "DomainRepositoryPublishedStateBoundary"),
                                    List.of("./gradlew compileJava", "./gradlew checkDomainEnforcement")),
                            row("domain-repository-foreign-applicationservice-routing-only", "Enforced",
                                    List.of("domain-repository bundle Error Prone", "DomainRepositoryRoleBoundary"),
                                    List.of("./gradlew checkDomainEnforcement"))))),
            Map.entry("domainUseCase", spec(
                    "docs/project/architecture/enforcement/domain-use-case-enforcement.md",
                    "domain-enforcement-coverage-complete",
                    "Domain UseCase enforcement coverage document is missing.",
                    "Could not read Domain UseCase enforcement coverage: ",
                    rows(
                            row("domain-usecase-direct-file-placement", "Enforced",
                                    List.of("domain-usecase bundle build-harness", "DomainUseCaseTopologyRules"),
                                    List.of("./gradlew checkDomainEnforcement")),
                            row("domain-root-usecase-cross-model-family-justification", "Enforced",
                                    List.of("domain-usecase bundle Error Prone", "DomainRootUseCaseCrossModelFamilyBoundary"),
                                    List.of("./gradlew compileJava", "./gradlew checkDomainEnforcement")),
                            row("domain-usecase-no-generic-bucket-names", "Enforced",
                                    List.of("domain-usecase bundle build-harness", "DomainUseCaseTopologyRules"),
                                    List.of("./gradlew checkDomainEnforcement")),
                            row("domain-usecase-no-backend-port-contract-files", "Enforced",
                                    List.of("domain-usecase bundle build-harness", "DomainUseCaseTopologyRules"),
                                    List.of("./gradlew checkDomainEnforcement")),
                            row("domain-usecase-no-same-context-published-dependencies", "Enforced",
                                    List.of("domain-usecase bundle Error Prone", "DomainApplicationNoSameContextPublishedDependency"),
                                    List.of("./gradlew compileJava", "./gradlew checkDomainEnforcement")),
                            row("domain-usecase-no-root-usecase-chains", "Enforced",
                                    List.of("domain-usecase bundle Error Prone", "DomainRootUseCaseNoRootUseCaseChains"),
                                    List.of("./gradlew compileJava", "./gradlew checkDomainEnforcement")),
                            row("domain-usecase-no-policy-helper-prefix-source-pattern", "Source-Pattern Enforced",
                                    List.of("domain-usecase bundle PMD", "DomainUseCasePolicyRule"),
                                    List.of("./gradlew checkDomainEnforcement")),
                            row("domain-usecase-collaborator-surface-discipline", "Enforced",
                                    List.of("domain-usecase bundle Error Prone", "DomainUseCaseRoleBoundary"),
                                    List.of("./gradlew compileJava", "./gradlew checkDomainEnforcement")),
                            row("domain-usecase-thin-orchestration-semantics", "Review-Owned"),
                            row("domain-usecase-no-hidden-business-policy", "Review-Owned"),
                            row("domain-usecase-no-hidden-carrier-bypass-into-model", "Review-Owned"),
                            row("domain-usecase-helper-role-discipline", "Review-Owned")))),
            Map.entry("layeringArchitecture", spec(
                    "docs/project/architecture/enforcement/layering-architecture-enforcement.md",
                    "layering-architecture-enforcement-coverage-complete",
                    "Layering Architecture enforcement document must exist.",
                    "Could not read layering architecture enforcement document: ",
                    rows(
                            row("layering-repository-active-java-root-allowlist", "Enforced",
                                    List.of("`layering-architecture-enforcement` bundle build-harness", "LayeringArchitectureTopologyRules"),
                                    List.of("./gradlew checkLayeringEnforcement")),
                            row("layering-repository-src-direct-child-allowlist", "Enforced",
                                    List.of("`layering-architecture-enforcement` bundle build-harness", "LayeringArchitectureTopologyRules"),
                                    List.of("./gradlew checkLayeringEnforcement")),
                            row("layering-repository-included-build-taxonomy", "Enforced",
                                    List.of("`layering-architecture-enforcement` bundle build-harness", "LayeringArchitectureTopologyRules"),
                                    List.of("./gradlew checkLayeringEnforcement")),
                            row("layering-intentional-cross-layer-public-boundary-set", "Enforced Elsewhere",
                                    List.of("view-layer-contribution-count", "domain-applicationservice-root-presence", "data-root-service-contribution-only"),
                                    List.of("see neighboring owner docs and their listed entrypoints")),
                            row("layering-no-extra-active-layer-roots", "Enforced",
                                    List.of("`layering-architecture-enforcement` bundle build-harness", "LayeringArchitectureTopologyRules"),
                                    List.of("./gradlew checkLayeringEnforcement")),
                            row("layering-no-undocumented-cross-layer-public-extension-points", "Review-Owned"),
                            row("layering-no-passive-carrier-shape-mirror-inside-feature-root", "Enforced",
                                    List.of("`layering-architecture-enforcement` bundle build-harness", "LayeringPassiveCarrierMirrorRules"),
                                    List.of("./gradlew checkLayeringEnforcement")),
                            row("layering-no-direct-view-data-dependency", "Enforced Elsewhere",
                                    List.of("PassiveViewInteractionBoundary", "ViewBinderDependencyBoundary"),
                                    List.of("./gradlew compileJava", "./gradlew checkViewEnforcement")),
                            row("layering-no-direct-view-domain-connection-outside-documented-seams", "Enforced Elsewhere",
                                    List.of(
                                            "view-binder-no-legacy-intenthandler-write-sink-injection",
                                            "view-intenthandler-root-applicationservice-boundary-surface"),
                                    List.of("see neighboring owner docs and their listed entrypoints")),
                            row("layering-no-non-applicationservice-public-backend-boundary-below-view", "Review-Owned"),
                            row("layering-no-outer-format-object-leak-inward", "Review-Owned"),
                            row("layering-no-domain-service-pass-through-wrapper", "Review-Owned"),
                            row("layering-no-domain-policy-pass-through-wrapper", "Review-Owned"),
                            row("layering-no-domain-factory-pass-through-wrapper", "Review-Owned"),
                            row("layering-no-domain-port-pass-through-wrapper", "Review-Owned"),
                            row("layering-no-domain-repository-pass-through-wrapper", "Review-Owned"),
                            row("layering-source-code-dependencies-point-inward", "Enforced Elsewhere",
                                    List.of("domainMustStayIndependentFromOuterLayers", "dataMustNotReachBootstrapOrPresentation"),
                                    List.of("./gradlew compileJava")),
                            row("layering-runtime-controlflow-reversal-only-through-documented-seams", "Review-Owned"),
                            row("layering-bootstrap-registration-order-and-generic-discovery-path", "Review-Owned"),
                            row("layering-view-domain-write-and-readback-seams-only", "Enforced Elsewhere",
                                    List.of("view-binder-no-legacy-intenthandler-write-sink-injection", "view-contentmodel-read-side-only-direct-boundary"),
                                    List.of("./gradlew compileJava", "./gradlew checkViewEnforcement")),
                            row("layering-no-third-presentation-state-mutation-route", "Review-Owned"),
                            row("layering-data-reaches-domain-only-through-public-boundaries-and-repositories", "Enforced Elsewhere",
                                    List.of("data-service-contribution-register-export-shape", "domain-repository-role-shape"),
                                    List.of("./gradlew compileJava", "./gradlew checkDomainEnforcement")),
                            row("layering-explicit-cross-layer-public-boundary-diagnostic", "Enforced",
                                    List.of("LayeringCrossLayerPublicBoundaryDependency"),
                                    List.of("./gradlew checkLayeringEnforcement")),
                            row("layering-thin-role-relay-stack-diagnostic", "Enforced",
                                    List.of("LayeringThinRoleRelayStackDiagnostic"),
                                    List.of("./gradlew checkLayeringEnforcement")),
                            row("layering-role-hub-sprawl-candidate", "Enforced",
                                    List.of("LayeringRoleHubSprawlCandidate"),
                                    List.of("./gradlew checkLayeringEnforcement")),
                            row("layering-cross-feature-sprawl-candidate", "Enforced",
                                    List.of("LayeringCrossFeatureSprawlCandidate"),
                                    List.of("./gradlew checkLayeringEnforcement")),
                            row("layering-public-boundary-breadth-candidate", "Enforced",
                                    List.of("LayeringPublicBoundaryBreadthCandidate"),
                                    List.of("./gradlew checkLayeringEnforcement"))))));

    private DocumentationCoverageCatalog() {
    }

    public static Specification specification(String id) {
        Specification specification = SPECIFICATIONS.get(id);
        if (specification == null) {
            throw new IllegalArgumentException("Unknown documentation coverage spec '" + id + "'.");
        }
        return specification;
    }

    private static Specification spec(
            String documentPath,
            String coverageRule,
            String missingDocumentMessage,
            String unreadableMessagePrefix,
            List<MarkdownTableCoverageValidator.ExpectedRow> expectedRows) {
        return new Specification(
                documentPath,
                coverageRule,
                missingDocumentMessage,
                unreadableMessagePrefix,
                expectedRows);
    }

    private static List<MarkdownTableCoverageValidator.ExpectedRow> rows(
            MarkdownTableCoverageValidator.ExpectedRow... expectedRows) {
        return List.of(expectedRows);
    }

    private static MarkdownTableCoverageValidator.ExpectedRow row(
            String ruleId,
            String status,
            List<String> ownerFragments,
            List<String> entrypoints) {
        return MarkdownTableCoverageValidator.row(ruleId, status, ownerFragments, entrypoints);
    }

    private static MarkdownTableCoverageValidator.ExpectedRow row(String ruleId, String status) {
        return MarkdownTableCoverageValidator.row(ruleId, status);
    }

    public record Specification(
            String documentPath,
            String coverageRule,
            String missingDocumentMessage,
            String unreadableMessagePrefix,
            List<MarkdownTableCoverageValidator.ExpectedRow> expectedRows
    ) {
    }
}
