// Auto-generated by scripts/generate-component-manifest.mjs
// Do not edit manually.
import type { LayoutElementComponent } from "./base";

import boxContainerComponent from "./components/box-container";
import dropdownComponent from "./components/dropdown";
import hboxContainerComponent from "./components/hbox-container";
import labelComponent from "./components/label";
import searchDropdownComponent from "./components/search-dropdown";
import separatorComponent from "./components/separator";
import textInputComponent from "./components/text-input";
import textareaComponent from "./components/textarea";
import vboxContainerComponent from "./components/vbox-container";
import viewContainerComponent from "./components/view-container";

export const COMPONENTS: LayoutElementComponent[] = [
    boxContainerComponent,
    dropdownComponent,
    hboxContainerComponent,
    labelComponent,
    searchDropdownComponent,
    separatorComponent,
    textInputComponent,
    textareaComponent,
    vboxContainerComponent,
    viewContainerComponent,
];
