// src/features/factions/simulation-types.ts
// Shared types for faction simulation

import type { FactionResources, FactionMember, FactionJob } from "@services/domain";

/**
 * Simulation tick - processes one day of faction activities
 */
export interface SimulationTick {
    /** Current game date (for calendar integration) */
    currentDate: string;
    /** Elapsed time in days since last tick */
    elapsedDays: number;
}

/**
 * Result of simulating one faction
 */
export interface FactionSimulationResult {
    /** Faction name */
    factionName: string;
    /** Resource changes this tick */
    resourceChanges: Partial<FactionResources>;
    /** Jobs that completed this tick */
    completedJobs: FactionJob[];
    /** New members recruited */
    newMembers: FactionMember[];
    /** Members that died/left */
    removedMembers: string[];
    /** Events generated (for timeline) */
    events: SimulationEvent[];
    /** Warnings/issues */
    warnings: string[];
}

/**
 * Event generated by simulation
 */
export interface SimulationEvent {
    /** Event title */
    title: string;
    /** Event description */
    description: string;
    /** Event type */
    type: "resource" | "conflict" | "discovery" | "completion" | "crisis";
    /** Importance (1-5, 5 = critical) */
    importance: number;
    /** Date when event occurs */
    date: string;
    /** Related faction */
    factionName: string;
}
