/**
 * Faction AI - Type definitions
 *
 * Defines types for faction AI decision-making, goal pursuit, and action planning.
 */

import type { FactionData, FactionMember, FactionResources } from "../../workmodes/library/factions/types";

/**
 * AI decision types available to factions
 */
export type FactionDecisionType =
    | "expand_territory"
    | "gather_resources"
    | "recruit_units"
    | "establish_camp"
    | "send_expedition"
    | "train_members"
    | "research_magic"
    | "build_structure"
    | "form_alliance"
    | "declare_war"
    | "raid_target"
    | "defend_territory"
    | "trade_resources"
    | "rest_and_recover";

/**
 * Result of AI decision evaluation
 */
export interface FactionDecision {
    /** Type of decision */
    type: FactionDecisionType;
    /** Priority score (0-100) - higher = more important */
    priority: number;
    /** Why this decision was chosen */
    reasoning: string;
    /** Required resources to execute */
    requiredResources?: Partial<FactionResources>;
    /** Expected outcome */
    expectedOutcome?: string;
    /** Time to complete (game days) */
    duration?: number;
    /** Specific parameters for this decision */
    params?: Record<string, any>;
}

/**
 * Context for AI decision-making
 */
export interface FactionAIContext {
    /** The faction making decisions */
    faction: FactionData;
    /** Current game time (for calendar integration) */
    currentDate?: string;
    /** Known neighboring factions */
    nearbyFactions?: FactionData[];
    /** Available hex positions for expansion */
    availableHexes?: Array<{ q: number; r: number; s: number }>;
    /** Active threats (hostile factions nearby) */
    threats?: string[];
    /** Active opportunities (resource-rich areas, weakened enemies) */
    opportunities?: string[];
}

/**
 * Action plan generated by AI
 */
export interface FactionActionPlan {
    /** The decision that generated this plan */
    decision: FactionDecision;
    /** Ordered steps to execute */
    steps: FactionActionStep[];
    /** Total estimated time */
    totalDuration: number;
    /** When this plan was created */
    createdAt: string;
    /** Plan status */
    status: "pending" | "in_progress" | "completed" | "failed" | "cancelled";
}

/**
 * Individual step in an action plan
 */
export interface FactionActionStep {
    /** Step ID */
    id: string;
    /** Description of what happens */
    description: string;
    /** Resources consumed */
    resourceCost?: Partial<FactionResources>;
    /** Resources produced */
    resourceGain?: Partial<FactionResources>;
    /** Members assigned to this step */
    assignedMembers?: string[]; // Member names
    /** Duration in game days */
    duration: number;
    /** Status */
    status: "pending" | "in_progress" | "completed" | "failed";
    /** Progress 0-100 */
    progress: number;
}

/**
 * Goal evaluation weights
 */
export interface GoalWeights {
    /** How important is territorial expansion? */
    expansion: number;
    /** How important is resource accumulation? */
    wealth: number;
    /** How important is military strength? */
    military: number;
    /** How important is magical power? */
    magic: number;
    /** How important is political influence? */
    influence: number;
    /** How important is stability/defense? */
    stability: number;
}

/**
 * Resource evaluation
 */
export interface ResourceEvaluation {
    /** Is the faction critically low on this resource? */
    critical: boolean;
    /** Current amount */
    current: number;
    /** Recommended minimum */
    minimum: number;
    /** Production rate (per day) */
    productionRate: number;
    /** Consumption rate (per day) */
    consumptionRate: number;
    /** Days until depleted (if negative consumption) */
    daysUntilDepletion?: number;
}
