package features.world.dungeonmap.ui.workspace.workflow;

import features.world.dungeonmap.domain.model.CorridorGeometry;
import features.world.dungeonmap.domain.model.DungeonLayout;
import features.world.dungeonmap.domain.model.DungeonCorridor;
import features.world.dungeonmap.domain.model.DungeonCorridorEndpoint;
import features.world.dungeonmap.domain.model.DungeonClusterEdgeRef;
import features.world.dungeonmap.domain.model.DungeonClusterVertexRef;
import features.world.dungeonmap.domain.model.DungeonRuntimeLocation;
import features.world.dungeonmap.domain.model.DungeonSelection;
import features.world.dungeonmap.domain.model.DungeonRoom;
import features.world.dungeonmap.domain.model.DungeonRoomCluster;
import features.world.dungeonmap.domain.model.Point2i;
import features.world.dungeonmap.ui.workspace.DungeonEditorTool;
import features.world.dungeonmap.ui.workspace.render.CorridorDoorHit;
import features.world.dungeonmap.ui.workspace.render.DungeonLayoutRenderData;
import features.world.dungeonmap.ui.workspace.workflow.state.DungeonPaneInteractionState;
import features.world.dungeonmap.ui.workspace.workflow.state.DungeonPreviewState;
import javafx.scene.input.MouseEvent;

import java.util.List;
import java.util.Set;

public interface DungeonPaneWorkflowHost {
    DungeonLayout dungeonLayout();
    DungeonLayoutRenderData renderData();
    DungeonSelection selectedTarget();
    DungeonRuntimeLocation activeLocation();
    void setLayoutState(DungeonLayout layout, DungeonLayoutRenderData renderData, DungeonSelection selectedTarget, DungeonRuntimeLocation activeLocation);
    boolean editable();
    DungeonEditorTool editorTool();
    void setEditorToolInternal(DungeonEditorTool editorTool);
    DungeonEditorSurface surface();
    DungeonPreviewState previewState();
    DungeonPaneInteractionState interactionState();
    DungeonPaneCallbacks callbacks();
    DungeonPreviewTopologySession previewTopologySession();
    void requestRender();
    Point2i worldPointAt(double screenX, double screenY);
    double worldX(double screenX);
    double worldY(double screenY);
    DungeonRoomCluster findClusterAt(double screenX, double screenY);
    DungeonRoom findRoomAt(double screenX, double screenY);
    DungeonCorridor findCorridorAt(double screenX, double screenY);
    DungeonClusterEdgeRef findClusterEdgeAt(double screenX, double screenY);
    DungeonClusterVertexRef findClusterVertexAt(double screenX, double screenY);
    List<DungeonClusterVertexRef> findClusterVerticesNear(double screenX, double screenY);
    DungeonClusterVertexRef findClusterVertexNear(long clusterId, double screenX, double screenY);
    CorridorDoorHit findCorridorDoorHitAt(double screenX, double screenY);
    CorridorEditInteractionController.DoorHandle findCorridorDoorHandleAt(double screenX, double screenY);
    CorridorEditInteractionController.DoorDragPreview corridorDoorDragPreviewAt(double screenX, double screenY, CorridorEditInteractionController.DoorHandle handle);
    CorridorEditInteractionController.WaypointHandle findCorridorWaypointHandleAt(double screenX, double screenY);
    CorridorEditInteractionController.WaypointHandle findCorridorWaypointRemoveHandleAt(double screenX, double screenY);
    CorridorEditInteractionController.SegmentInsertHit findCorridorSegmentInsertHitAt(double screenX, double screenY);
    DungeonCorridorEndpoint corridorEndpointLocationAt(double screenX, double screenY, DungeonRoom room, DungeonCorridor corridor);
    DungeonRoomCluster findClusterInSelection(Point2i startInclusive, Point2i endInclusive);
    boolean canCreateGraphRoomAt(Point2i world);
    boolean updateCorridorPressMode(MouseEvent event);
    CorridorEditInteractionController.PressMode corridorPressMode();
    CorridorEditInteractionController controller();
    WallPathInteractionController wallPathController();
    void rebuildClusterDragPreview();
    void clearSelectionPreview();
    void clearPaintPreview();
    void rebuildPaintPreviewCells();
    void applySelectedCorridorDoorHandle(CorridorEditInteractionController.DoorHandle handle, boolean notify, boolean renderNow);
    CorridorEditInteractionController.DoorHandle selectedCorridorDoorHandle();
    boolean clearCorridorDoorPreview();
    boolean updateCorridorDoorPreview(CorridorEditInteractionController.DoorHandle handle, CorridorEditInteractionController.DoorDragPreview preview);
    boolean updateHoveredCorridorAt(double screenX, double screenY);
    boolean clearHoveredCorridor();
    void updatePointerPosition(MouseEvent event);
    void refreshHoverAfterProjectionChange();
    void updateDragPreview(DungeonPaneInteractionState.DragInteraction dragInteraction, Point2i world);
    void commitDrag(DungeonPaneInteractionState.DragInteraction dragInteraction, Point2i world);
    void commitSelection(Point2i start, Point2i end);
    void beginSelection(Point2i world);
    void updateSelectionPreview(Point2i world);
    void beginPaint(Point2i world);
    void updatePaintPreview(Point2i world);
    void commitPaint(Point2i world);
    void onPointerExited();
    Set<Point2i> previewPaintCells();
    CorridorGeometry corridorGeometryForDisplay(DungeonCorridor corridor);
    Set<Point2i> clusterCellsFor(DungeonRoomCluster cluster);
    DungeonRoomCluster clusterById(long clusterId);
}
