// Creature-Presets für CLI-Testing und Plugin-Bundling
// Siehe: docs/entities/creature.md

import { z } from 'zod';
import { creatureDefinitionSchema } from '../../src/types/entities/creature';

// ============================================================================
// PRESET-SCHEMA
// ============================================================================

/**
 * Schema für Creature-Presets.
 * Erweitert creatureDefinitionSchema um Preset-spezifische Defaults.
 */
export const creaturePresetSchema = creatureDefinitionSchema;

/**
 * Schema für die gesamte Preset-Collection.
 */
export const creaturePresetsSchema = z.array(creaturePresetSchema);

// ============================================================================
// PRESET-DATEN
// ============================================================================

export const creaturePresets = creaturePresetsSchema.parse([
  {
    id: 'goblin',
    name: 'Goblin',
    cr: 0.25,
    maxHp: 7,
    ac: 15,
    size: 'small',
    tags: ['humanoid', 'goblinoid'],
    species: 'goblin',
    disposition: 'hostile',
    terrainAffinities: ['forest', 'hills', 'cave'],
    activeTime: ['dawn', 'morning', 'midday', 'afternoon', 'dusk', 'night'],
    designRole: 'skirmisher',
    groupSize: { min: 4, avg: 6, max: 12 },
    activities: ['ambush', 'patrol', 'scavenge'],
    preferences: {
      weather: { avoids: ['rain', 'heavy_rain'] },
    },
    lootTags: ['weapon-simple', 'armor-light', 'coins-poor'],
    carriesLoot: true,
    detectionProfile: {
      noiseLevel: 'normal',
      scentStrength: 'moderate',
    },
    abilities: { str: 8, dex: 14, con: 10, int: 10, wis: 8, cha: 8 },
    speed: { walk: 30 },
    senses: { passivePerception: 9, darkvision: 60 },
    languages: ['Common', 'Goblin'],
    source: 'MM',
  },
  {
    id: 'wolf',
    name: 'Wolf',
    cr: 0.25,
    maxHp: 11,
    ac: 13,
    size: 'medium',
    tags: ['beast'],
    species: 'wolf',
    disposition: 'hostile',
    terrainAffinities: ['forest', 'hills', 'plains'],
    activeTime: ['dawn', 'dusk', 'night'],
    designRole: 'skirmisher',
    groupSize: { min: 3, avg: 5, max: 8 },
    activities: ['hunt', 'patrol'],
    preferences: {
      weather: { prefers: ['snow', 'blizzard'] },
    },
    lootTags: ['pelt', 'teeth'],
    carriesLoot: false,
    detectionProfile: {
      noiseLevel: 'quiet',
      scentStrength: 'strong',
    },
    abilities: { str: 12, dex: 15, con: 12, int: 3, wis: 12, cha: 6 },
    speed: { walk: 40 },
    senses: { passivePerception: 13 },
    languages: [],
    source: 'MM',
  },
  {
    id: 'bandit',
    name: 'Bandit',
    cr: 0.125,
    maxHp: 11,
    ac: 12,
    size: 'medium',
    tags: ['humanoid', 'human'],
    species: 'human',
    disposition: 'hostile',
    terrainAffinities: ['forest', 'hills', 'road'],
    activeTime: ['morning', 'midday', 'afternoon', 'dusk'],
    designRole: 'soldier',
    groupSize: { min: 2, avg: 4, max: 8 },
    activities: ['ambush', 'camp', 'travel'],
    preferences: {
      weather: { avoids: ['heavy_rain'] },
    },
    lootTags: ['weapon-simple', 'armor-light', 'coins-poor', 'supplies'],
    carriesLoot: true,
    detectionProfile: {
      noiseLevel: 'normal',
      scentStrength: 'faint',
    },
    abilities: { str: 11, dex: 12, con: 12, int: 10, wis: 10, cha: 10 },
    speed: { walk: 30 },
    senses: { passivePerception: 10 },
    languages: ['Common'],
    source: 'MM',
  },
  {
    id: 'owlbear',
    name: 'Owlbear',
    cr: 3,
    maxHp: 59,
    ac: 13,
    size: 'large',
    tags: ['monstrosity'],
    species: 'owlbear',
    disposition: 'hostile',
    terrainAffinities: ['forest'],
    activeTime: ['dawn', 'morning', 'midday', 'afternoon', 'dusk'],
    designRole: 'brute',
    groupSize: 1,
    activities: ['hunt', 'lair'],
    preferences: {
      weather: { prefers: ['rain', 'drizzle'] },
    },
    lootTags: ['feathers', 'claws'],
    carriesLoot: false,
    detectionProfile: {
      noiseLevel: 'loud',
      scentStrength: 'strong',
    },
    abilities: { str: 20, dex: 12, con: 17, int: 3, wis: 12, cha: 7 },
    speed: { walk: 40 },
    senses: { passivePerception: 13, darkvision: 60 },
    languages: [],
    source: 'MM',
  },
  {
    id: 'skeleton',
    name: 'Skeleton',
    cr: 0.25,
    maxHp: 13,
    ac: 13,
    size: 'medium',
    tags: ['undead'],
    species: 'skeleton',
    disposition: 'hostile',
    terrainAffinities: ['cave', 'ruins', 'graveyard'],
    activeTime: ['night'],
    designRole: 'minion',
    groupSize: { min: 3, avg: 6, max: 12 },
    activities: ['guard', 'patrol'],
    lootTags: ['weapon-simple', 'armor-light'],
    carriesLoot: true,
    detectionProfile: {
      noiseLevel: 'quiet',
      scentStrength: 'none',
    },
    abilities: { str: 10, dex: 14, con: 15, int: 6, wis: 8, cha: 5 },
    speed: { walk: 30 },
    senses: { passivePerception: 9, darkvision: 60 },
    languages: [],
    source: 'MM',
  },
  {
    id: 'hobgoblin',
    name: 'Hobgoblin',
    cr: 0.5,
    maxHp: 11,
    ac: 18,
    size: 'medium',
    tags: ['humanoid', 'goblinoid'],
    species: 'hobgoblin',
    disposition: 'hostile',
    terrainAffinities: ['forest', 'hills', 'cave', 'plains'],
    activeTime: ['dawn', 'morning', 'midday', 'afternoon', 'dusk', 'night'],
    designRole: 'soldier',
    groupSize: { min: 2, avg: 4, max: 6 },
    activities: ['patrol', 'guard', 'ambush'],
    preferences: {
      weather: { avoids: ['heavy_rain'] },
    },
    lootTags: ['weapon-martial', 'armor-medium', 'coins-poor'],
    carriesLoot: true,
    detectionProfile: {
      noiseLevel: 'normal',
      scentStrength: 'moderate',
    },
    abilities: { str: 13, dex: 12, con: 12, int: 10, wis: 10, cha: 9 },
    speed: { walk: 30 },
    senses: { passivePerception: 10, darkvision: 60 },
    languages: ['Common', 'Goblin'],
    source: 'MM',
  },
  {
    id: 'goblin-boss',
    name: 'Goblin Boss',
    cr: 1,
    maxHp: 21,
    ac: 17,
    size: 'small',
    tags: ['humanoid', 'goblinoid'],
    species: 'goblin',
    disposition: 'hostile',
    terrainAffinities: ['forest', 'hills', 'cave'],
    activeTime: ['dawn', 'morning', 'midday', 'afternoon', 'dusk', 'night'],
    designRole: 'leader',
    groupSize: 1,
    activities: ['command', 'ambush', 'patrol'],
    preferences: {
      weather: { avoids: ['rain', 'heavy_rain'] },
    },
    lootTags: ['weapon-simple', 'armor-light', 'coins-moderate', 'trinket'],
    carriesLoot: true,
    detectionProfile: {
      noiseLevel: 'normal',
      scentStrength: 'moderate',
    },
    abilities: { str: 10, dex: 14, con: 10, int: 10, wis: 8, cha: 10 },
    speed: { walk: 30 },
    senses: { passivePerception: 9, darkvision: 60 },
    languages: ['Common', 'Goblin'],
    source: 'MM',
  },
  {
    id: 'bandit-captain',
    name: 'Bandit Captain',
    cr: 2,
    maxHp: 65,
    ac: 15,
    size: 'medium',
    tags: ['humanoid', 'human'],
    species: 'human',
    disposition: 'hostile',
    terrainAffinities: ['forest', 'hills', 'road', 'coast'],
    activeTime: ['morning', 'midday', 'afternoon', 'dusk'],
    designRole: 'leader',
    groupSize: 1,
    activities: ['command', 'ambush', 'camp'],
    preferences: {
      weather: { avoids: ['heavy_rain'] },
    },
    lootTags: ['weapon-martial', 'armor-medium', 'coins-moderate', 'jewelry'],
    carriesLoot: true,
    detectionProfile: {
      noiseLevel: 'normal',
      scentStrength: 'faint',
    },
    abilities: { str: 15, dex: 16, con: 14, int: 14, wis: 11, cha: 14 },
    speed: { walk: 30 },
    senses: { passivePerception: 10 },
    languages: ['Common', 'Thieves Cant'],
    source: 'MM',
  },
  {
    id: 'thug',
    name: 'Thug',
    cr: 0.5,
    maxHp: 32,
    ac: 11,
    size: 'medium',
    tags: ['humanoid', 'human'],
    species: 'human',
    disposition: 'hostile',
    terrainAffinities: ['forest', 'road', 'coast', 'urban'],
    activeTime: ['morning', 'midday', 'afternoon', 'dusk', 'night'],
    designRole: 'brute',
    groupSize: { min: 2, avg: 3, max: 4 },
    activities: ['guard', 'intimidate', 'ambush'],
    lootTags: ['weapon-simple', 'armor-light', 'coins-poor'],
    carriesLoot: true,
    detectionProfile: {
      noiseLevel: 'normal',
      scentStrength: 'faint',
    },
    abilities: { str: 15, dex: 11, con: 14, int: 10, wis: 10, cha: 11 },
    speed: { walk: 30 },
    senses: { passivePerception: 10 },
    languages: ['Common'],
    source: 'MM',
  },
]);

// Default-Export für einfachen Import
export default creaturePresets;
